import createInstance, { getFromConfig } from './baseService'

// ====================================== Create Instance ======================================
// **** Parameters ****
const serviceName = 'excavation'

// getFromConfig(configName: string, district: string, appendJson = true) => baseUrl: string
const getBaseUrl = ({ District, payload, config }) => getFromConfig(serviceName, District, true)
// **** Parameters ****

// **** Request Configuration ****
const { createPostRequest } = createInstance({
  getBaseUrl,
  serviceName,
  headers: {},
  requestCallback: null, // (axiosConfig) => axiosConfig
  responseCallback: null // (axiosResponse) => new Response
  // encryption: false
})
// **** Request Configuration ****
// ====================================== Create Instance ======================================

export const getAssignRequestToUser = createPostRequest('/GetAssignRequestToUser')
export const getRequestServiceInfoWithNidProc = createPostRequest('/GetRequestService_InfoWithNidProc')
export const getBayganiItem = createPostRequest('/GetBayganiItem')
export const cancelRequestinEsup = createPostRequest('/CancelRequestinEsup')
export const saveRequestServiceInfo = createPostRequest('/SaveRequestService_Info')
export const getInquiry = createPostRequest('/GetInquiry')
export const decodeAndConfirmBankFile = createPostRequest('/DecodeAndConfirmBankFile')
export const getIncomePaymentInFicheNo = createPostRequest('/GetIncome_PaymentInFicheNo')
export const getRequestForCancelRenewal = createPostRequest('/GetRequestForCancelRenewal')
export const cancelRenewal = createPostRequest('/CancelRenewal')
export const saveIncomePayment = createPostRequest('/SaveIncome_Payment')
export const saveAssignRequestToUser = createPostRequest('/SaveAssignRequestToUser')
export const getRenewedExpaireInquries = createPostRequest('/GetRenewedExpaireInquries')
export const sendRenewedExpaireInquries = createPostRequest('/SendRenewedExpaireInquries')
export const decodeAndConfirmViaWebService = createPostRequest('/DecodeAndConfirmViaWebService')
export const getCI = createPostRequest('/GetCI')
export const getIncomeFiche = createPostRequest('/GetIncomeFiche')
export const getFormValidation = createPostRequest('/GetFormValidation')
export const loadLayout = createPostRequest('/LoadLayout')
export const getRunMonitoringKartabl = createPostRequest('/GetRunMonitoringKartabl')
export const getAccountingDocNotSentList = createPostRequest('/GetAccounting_DocNotSentList')
export const searchInBlackList = createPostRequest('/SearchInBlackList')
export const getSearch = createPostRequest('/GetSerach')
export const getLicenceExport = createPostRequest('/GetLicenceExport')
export const saveTimeLicenceExport = createPostRequest('/SaveTimeLicenceExport')
export const setApproval = createPostRequest('/SetApproval')
export const saveExportLicenseComments = createPostRequest('/SaveExportLicenseComments')
export const saveExportLicenseMayorComment = createPostRequest('/SaveExportLicenseMayorComment')
export const getRevisitRenewalRequest = createPostRequest('/GetRevisitRenewal_Request')

export const getCIPathType = createPostRequest('/GetCI_PathType')
export const getCIRegion = createPostRequest('/GetCI_Region')
export const getCIDigType = createPostRequest('/GetCI_DigType')
export const getCIDigTime = createPostRequest('/GetCI_DigTime')
export const getCIOperationLevel = createPostRequest('/GetCI_OperationLevel')
export const getCICoefficientA = createPostRequest('/GettCI_CoefficientA')
export const getCICoefficient = createPostRequest('/GetCI_Coefficient')
export const getCITextureType = createPostRequest('/GetCI_TextureType')
export const getClsCIAsphaltType = createPostRequest('/GetClsCI_AsphaltType')
export const getCIBaseCost = createPostRequest('/GetCI_BaseCost')
export const getCIOverheadCoefficient = createPostRequest('/GetCI_OverheadCoefficient')
export const getCIUnitPriceRequest = createPostRequest('/GetCI_UnitPriceRequest')
export const getClsCIMaterialsType = createPostRequest('/GetClsCI_MaterialsType')
export const getClsCIPossibledamage = createPostRequest('/GetClsCI_Possibledamage')
export const getClsCIDiggings = createPostRequest('/GetClsCI_Diggings')
export const getClsCICompanyType = createPostRequest('/GetClsCI_CompanyType')
export const getClsCIRequesterType = createPostRequest('/GetClsCI_RequesterType')
export const getInActiveInquiriesReport = createPostRequest('/GetInActiveInquiriesReport')
export const getAcceptInquiry = createPostRequest('/GetAcceptInquiry')
export const acceptInquiry = createPostRequest('/AcceptInquiry')
export const getIncomeFichebyNidProc = createPostRequest('/GetIncomeFichebyNidProc')
export const getAllRequestServiceRunMonitoringHeaders = createPostRequest('/GetAllRequestService_RunMonitoringHeaders')

export const getClsCIPhase = createPostRequest('/GetClsCI_Phase')
export const getClsCIYears = createPostRequest('/GetClsCI_Years')
export const getClsCICrossType = createPostRequest('/GetClsCI_CrossType')
export const getClsCIAsphaltQuality = createPostRequest('/GetClsCI_AsphaltQuality')
export const getClsCIDigRepeat = createPostRequest('/GetClsCI_DigRepeat')
export const getAllCompanyInfo = createPostRequest('/GetAllCompanyInfo')
export const getClsCIRedirectName = createPostRequest('/GetClsCI_RedirectName')
export const getClsCISection = createPostRequest('/GetClsCI_Section')
export const getClsCIProject = createPostRequest('/GetClsCI_Project')
export const getClsCIBlackListCause = createPostRequest('/GetClsCI_BlackListCause')
export const getCIInstrument = createPostRequest('/GetCI_Instrument')
export const getClsCIScouring = createPostRequest('/GetClsCI_Scouring')
export const getClsSmsInfo = createPostRequest('/GetClsSmsInfo')
export const getClsCIPosition = createPostRequest('/GetClsCI_Position')

export const getClsRepairCost = createPostRequest('/GetClsRepairCost')
export const getClsCIRunMonitoring = createPostRequest('/GetClsCI_RunMonitoring')
export const getClsCIRunMonitoringType = createPostRequest('/GetClsCI_RunMonitoringType')
export const getClsCIRunMonitoringStatus = createPostRequest('/GetClsCI_RunMonitoringStatus')
export const getClsCIInstallation = createPostRequest('/GetClsCI_Installation')
export const getClsCICauseRenewal = createPostRequest('/GetClsCI_CauseRenewal')
export const getClsCIDeliveryInstallationsType = createPostRequest('/GetClsCI_Delivery_InstallationsType')
export const getClsCIDefectsSubject = createPostRequest('/GetClsCI_DefectsSubject')

export const saveCIPathType = createPostRequest('/SaveCI_PathType')
export const saveClsSmsInfo = createPostRequest('/SaveClsSmsInfo')
export const saveCIRegion = createPostRequest('/SaveCI_Region')
export const saveCIDigType = createPostRequest('/SaveCI_DigType')
export const saveCIDigTime = createPostRequest('/SaveCI_DigTime')
export const saveCIOperationLevel = createPostRequest('/SaveCI_OperationLevel')
export const saveCICoefficientA = createPostRequest('/SavetCI_CoefficientA')
export const saveCICoefficient = createPostRequest('/SaveCI_Coefficient')
export const saveCITextureType = createPostRequest('/SaveCI_TextureType')
export const saveClsCIAsphaltType = createPostRequest('/SaveClsCI_AsphaltType')
export const saveCIBaseCost = createPostRequest('/SaveCI_BaseCost')
export const saveCIOverheadCoefficient = createPostRequest('/SaveCI_OverheadCoefficient')
export const saveCIUnitPriceRequest = createPostRequest('/SaveCI_UnitPriceRequest')
export const saveClsCIMaterialsType = createPostRequest('/SaveCI_MaterialsType')
export const saveClsCIPossibledamage = createPostRequest('/SaveCI_Possibledamage')
export const saveClsCIDiggings = createPostRequest('/SaveClsCI_Diggings')
export const saveClsCICompanyType = createPostRequest('/SaveClsCI_CompanyType')
export const saveClsCIRequesterType = createPostRequest('/SaveClsCI_RequesterType')

export const saveClsCIPhase = createPostRequest('/SaveClsCI_Phase')
export const saveClsCIYears = createPostRequest('/SaveClsCI_Years')
export const saveClsCICrossType = createPostRequest('/SaveClsCI_CrossType')
export const saveClsCIAsphaltQuality = createPostRequest('/SaveClsCI_AsphaltQuality')
export const saveClsCIDigRepeat = createPostRequest('/SaveClsCI_DigRepeat')
export const saveAllCompanyInfo = createPostRequest('/SaveAllCompanyInfo')
export const saveClsCIRedirectName = createPostRequest('/SaveClsCI_RedirectName')
export const saveClsCISection = createPostRequest('/SaveClsCI_Section')
export const saveClsCIProject = createPostRequest('/SaveClsCI_Project')
export const saveClsCIBlackListCause = createPostRequest('/SaveClsCI_BlackListCause')
export const saveCIInstrument = createPostRequest('/SaveClsCI_Instrument')
export const saveClsCIScouring = createPostRequest('/SaveClsCI_Scouring')
export const saveClsCIPosition = createPostRequest('/SaveClsCI_Position')

export const saveClsRepairCost = createPostRequest('/SaveClsRepairCost')
export const saveClsCIRunMonitoring = createPostRequest('/SaveClsCI_RunMonitoring')
export const saveClsCIRunMonitoringType = createPostRequest('/SaveClsCI_RunMonitoringType')
export const saveClsCIRunMonitoringStatus = createPostRequest('/SaveClsCI_RunMonitoringStatus')
export const saveClsCIInstallation = createPostRequest('/SaveClsCI_Installation')
export const saveClsCICauseRenewal = createPostRequest('/SaveClsCI_CauseRenewal')
export const saveClsCIDeliveryInstallationsType = createPostRequest('/SaveClsCI_Delivery_InstallationsType')
export const saveClsCIDefectsSubject = createPostRequest('/SaveClsCI_DefectsSubject')
export const getExportRenewalReport = createPostRequest('/GetExportRenewalReport')
export const saveRequestInfo = createPostRequest('/SaveRequest_Info')
export const getRequestInfoWithNidProc = createPostRequest('/GetGetRequest_InfoWithNidProc')
export const saveConfirmFicheIncomePayment = createPostRequest('/SaveConfirmFicheIncome_Payment')
export const getArchiveRootSubject = createPostRequest('/GetArchiveRootSubject ')
export const getInquiryRenewedHistory = createPostRequest('/GetInquiryRenewedHistory ')

export const getAllBlackList = createPostRequest('/GetAllBlackList')
export const getBlackList = createPostRequest('/GetBlackList')
export const deleteBlackListInfo = createPostRequest('/DeleteBlackListInfo')
export const saveBlackList = createPostRequest('/Save_BlackList')
export const deleteAccountingDocNotSent = createPostRequest('/DeleteAccounting_DocNotSent')

export const getRequestReport = createPostRequest('/GetRequestReport')
export const getExportLicenseReport = createPostRequest('/GetExportLicenseReport')
export const createLayerMap = createPostRequest('/CreateLayerMap')
export const getAllRequestRunMonitoringHeaders = createPostRequest('/GetAllRequest_RunMonitoringHeaders')
export const getPolygon = createPostRequest('/GetPolygon')
export const getRequestRunMonitoring = createPostRequest('/GetRequest_RunMonitoring')
export const inquiryReport = createPostRequest('/InquiryReport')
export const saveInquiry = createPostRequest('/SaveInquiry')
export const reSendToFinancialSystem = createPostRequest('/ReSendToFinancialSystem')
export const baygani = createPostRequest('/Baygani')
export const exitBaygani = createPostRequest('/ExitBaygani')
export const getRequestServiceRunMonitoring = createPostRequest('/GetRequestService_RunMonitoring')
export const deleteRequestRunMonitoring = createPostRequest('/DeleteRequest_RunMonitoring')
export const inquiryReportRenewed = createPostRequest('/InquiryReportRenewed')
export const getSubIncomeFiche = createPostRequest('/GetSubIncomeFiche')
export const getRenewalRequest = createPostRequest('/GetRenewal_Request')
export const saveRenewalRequest = createPostRequest('/SaveRenewal_Request')
export const getDelivery = createPostRequest('/GetDelivery')
export const saveDelivery = createPostRequest('/SaveDelivery')
export const getRenewalRequestService = createPostRequest('/GetRenewal_RequestService')
export const saveRenewalRequestService = createPostRequest('/SaveRenewal_RequestService')
export const getRenewedInquries = createPostRequest('/GetRenewedInquries')
export const getBazdidHouse = createPostRequest('/GetBazdid_House')
export const getRequestData = createPostRequest('/GetRequestData')
export const getRevisitRequestWithNidProc = createPostRequest('/GetRevisit_RequestWithNidProc')
export const getRevisitRequestServiceWithNidProc = createPostRequest('/GetRevisit_RequestServiceWithNidProc')
export const getCommitteeLicense = createPostRequest('/GetCommitteeLicense')
export const getCiArrangements = createPostRequest('/GetCi_Arrangements')
export const saveCommitteeLicense = createPostRequest('/SaveCommitteeLicense')

export const getAsphaltLabLevel1 = createPostRequest('/GetAsphaltLabLevel1')
export const saveClsAsphaltLabLevel1 = createPostRequest('/SaveClsAsphaltLabLevel1')

export const getAsphaltLabLevel2 = createPostRequest('/GetAsphaltLabLevel2')
export const saveClsAsphaltLabLevel2 = createPostRequest('/SaveClsAsphaltLabLevel2')

export const getLicenceInfo = createPostRequest('/GetLicenceInfo')
export const saveIncome = createPostRequest('/SaveIncome')
export const confirmOrCancelFiche = createPostRequest('/ConfirmOrCancelFiche')

export const saveRevisitRequestService = createPostRequest('/SaveRevisit_RequestService')

export const saveRevisitRequest = createPostRequest('/SaveRevisit_Request')

export const getRevisitRenewalRequestService = createPostRequest('/GetRevisitRenewal_RequestService')
export const saveRevisitRenewalRequestService = createPostRequest('/SaveRevisitRenewal_RequestService')
export const initMadule = createPostRequest('/InitMadule')
export const sendSms = createPostRequest('/SendSms')

export const delOddmentAccount = createPostRequest('/DelOddmentAccount')
export const saveOddmentAccount = createPostRequest('/SaveOddmentAccount')
export const cancelFiches = createPostRequest('/CancelFiches')

export const getIncomePayment = createPostRequest('/GetIncome_Payment')
export const saveIncomePaymentOnLine = createPostRequest('/SaveIncome_PaymentOnLine')
export const confirmOrCancel = createPostRequest('/ConfirmOrCancel')
export const addToArchive = createPostRequest('/AddToArchive')
export const setApprovalTaskResult = createPostRequest('/SetApprovalTaskResult')
export const getApprovalTask = createPostRequest('/GetApprovalTask')
export const checkBlackListInExportLicence = createPostRequest('/CheckBlackListInExportLicence')
export const getInstallment = createPostRequest('/GetInstallment')
export const installmentPerformance = createPostRequest('/InstallmentPerformance')
export const saveInstallment = createPostRequest('/SaveInstallment')
