import createInstance, { getFromConfig } from './baseService'
import endpoints from 'src/config/endpoints'

// ====================================== Create Instance ======================================

// **** Parameters ****
const serviceName = 'SC'

// getFromConfig(configName: string, district: string, appendJson = true) => baseUrl: string
const getBaseUrl = ({ District, payload, config }) => getFromConfig(serviceName, District, true)
// **** Parameters ****

// **** Request Configuration ****
const { createPostRequest } = createInstance({
  getBaseUrl,
  serviceName,
  headers: {},
  requestCallback: null, // (axiosConfig) => axiosConfig
  responseCallback: null // (axiosResponse) => new Response
})
// **** Request Configuration ****

// ====================================== Create Instance ======================================

export const getRequestListCanAttach = createPostRequest(endpoints.SC.getRequestListCanAttach)
export const getParvandehBlock = createPostRequest(endpoints.SC.getParvandehBlock)
export const getUrbanView = createPostRequest('GetUrbanView')
export const addFileToArchive = createPostRequest('AddFileToArchive')
export const getWFNodeReturnMapping = createPostRequest('GetWF_NodeReturnMapping')
export const SaveUrbanView = createPostRequest('SaveUrbanView')
export const getMojazParvanehHouseSharing = createPostRequest('GetMojazParvaneh_HouseSharing')
export const saveMojazParvanehHouseSharing = createPostRequest('SaveMojazParvaneh_HouseSharing')
export const deleteRequest = createPostRequest('DeleteRequest')
// export const deleteProc  = createPostRequest('DeleteProc')
export const deleteProc = createPostRequest(endpoints.SC.deleteProc)
export const hasArchiveBizCodeInNosaziCode = createPostRequest(endpoints.SC.hasArchiveBizCodeInNosaziCode)
export const mapArchiveBizCodeToNosaziCode = createPostRequest(endpoints.SC.mapArchiveBizCodeToNosaziCode)
export const getParvandehHouse = createPostRequest(endpoints.SC.getParvandehHouse)
export const getParvandehBuilding = createPostRequest(endpoints.SC.getParvandehBuilding)
export const getParvandehApartment = createPostRequest(endpoints.SC.getParvandehApartment)
export const getFilInfo = createPostRequest(endpoints.SC.getFilInfo)
// export const getFilInfo =
//   createPostRequest('/GetFil_Info')
export const getParvandehHouseSharing = createPostRequest(endpoints.SC.getParvandehHouseSharing)
export const getParvandehShop = createPostRequest(endpoints.SC.getParvandehShop)
export const getRevisitList = createPostRequest(endpoints.SC.getRevisitList)
export const getAssignRevisitInfo = createPostRequest(endpoints.SC.getAssignRevisitInfo)
export const loadBarokaf = createPostRequest(endpoints.SC.loadBarokaf)
export const loadBarokafHistory = createPostRequest(endpoints.SC.loadBarokafHistory)
export const saveParvandehBlock = createPostRequest(endpoints.SC.saveParvandehBlock)
export const saveParvandehHouse = createPostRequest(endpoints.SC.saveParvandehHouse)
export const saveParvandehBuilding = createPostRequest(endpoints.SC.saveParvandehBuilding)
export const saveParvandehApartment = createPostRequest(endpoints.SC.saveParvandehApartment)
export const saveParvandehHouseSharing = createPostRequest(endpoints.SC.saveParvandehHouseSharing)
export const saveParvandehShop = createPostRequest(endpoints.SC.saveParvandehShop)
export const loadTarhTafsili = createPostRequest(endpoints.SC.loadTarhTafsili)
export const saveTarhTafsili = createPostRequest(endpoints.SC.saveTarhTafsili)
export const loadMovafeghatOsooli = createPostRequest(endpoints.SC.loadMovafeghatOsooli)
export const saveMovafeghatOsooli = createPostRequest(endpoints.SC.saveMovafeghatOsooli)
export const confirmOutput = createPostRequest(endpoints.SC.confirmOutput)
export const reportValidation = createPostRequest(endpoints.SC.reportValidation)
export const copyFromRevisitToOneOfMovafeghatOsooli = createPostRequest(endpoints.SC.copyFromRevisitToOneOfMovafeghatOsooli)
export const copyToMojazPayankar = createPostRequest(endpoints.SC.copyToMojazPayankar)
export const copyHouseSharingToMojazParvaneh = createPostRequest(endpoints.SC.copyHouseSharingToMojazParvaneh)
export const copyBuildingToMojazParvaneh = createPostRequest(endpoints.SC.copyBuildingToMojazParvaneh)
export const copyFromMojazParvanehToBuildingParvandeh = createPostRequest(endpoints.SC.copyFromMojazParvanehToBuildingParvandeh)
export const copyHistoryToBarokaf = createPostRequest(endpoints.SC.copyHistoryToBarokaf)
export const loadPayankar = createPostRequest(endpoints.SC.loadPayankar)
export const savePayankar = createPostRequest(endpoints.SC.savePayankar)
export const loadMapControl = createPostRequest(endpoints.SC.loadMapControl)
export const copyFromMovafeghatOsooliToMapControl = createPostRequest(endpoints.SC.copyFromMovafeghatOsooliToMapControl)
export const loadMapControlHistory = createPostRequest(endpoints.SC.loadMapControlHistory)
export const copyChidemanToMapControl = createPostRequest(endpoints.SC.copyChidemanToMapControl)
export const copyRevisitToMapControl = createPostRequest(endpoints.SC.copyRevisitToMapControl)
export const copyMojazParvanehToMapControl = createPostRequest(endpoints.SC.copyMojazParvanehToMapControl)
export const copyMapControlEngineerToOtherGroups = createPostRequest(endpoints.SC.copyMapControlEngineerToOtherGroups)
export const getBarghInquiryData = createPostRequest(endpoints.SC.GetBarghInquiryData)
export const loadZabetehChideman = createPostRequest(endpoints.SC.loadZabetehChideman)
export const loadPlanOrder = createPostRequest(endpoints.SC.loadPlanOrder)
export const loadParvaneh = createPostRequest(endpoints.SC.loadParvaneh)
export const loadMissFoul = createPostRequest(endpoints.SC.loadMissFoul)
export const loadMafasaComments = createPostRequest(endpoints.SC.loadMafasaComments)
export const exportMafasa = createPostRequest(endpoints.SC.exportMafasa)
export const loadRequestInfo = createPostRequest(endpoints.SC.loadRequestInfo)
export const getAllRequestList = createPostRequest(endpoints.SC.getAllRequestList)
export const saveRequestInfo = createPostRequest(endpoints.SC.saveRequestInfo)
export const checkValidationForBlackListBeforSaveRequest = createPostRequest(endpoints.SC.checkValidationForBlackListBeforSaveRequest)
export const updateLastRequestState = createPostRequest(endpoints.SC.updateLastRequestState)
export const getCIRequestInquiryKindFromNidWorkflowDeff = createPostRequest('GetCI_RequestInquiryKind_FromNidWorkflowDeff')
export const getTajmiHistoryList = createPostRequest(endpoints.SC.getTajmiHistoryList)
export const changeNosaziCode = createPostRequest(endpoints.SC.changeNosaziCode)
export const deleteNosaziCode = createPostRequest(endpoints.SC.deleteNosaziCode)
export const transferNosaziCode = createPostRequest(endpoints.SC.transferNosaziCode)
export const saveNosaziCode = createPostRequest(endpoints.SC.saveNosaziCode)
export const clone = createPostRequest(endpoints.SC.clone)
export const convertHouseToApartment = createPostRequest(endpoints.SC.convertHouseToApartment)
export const getMojazParvanehHouse = createPostRequest(endpoints.SC.getMojazParvanehHouse)
export const saveMojazParvanehHouse = createPostRequest(endpoints.SC.saveMojazParvanehHouse)
export const getMojazPayankarHouse = createPostRequest(endpoints.SC.getMojazPayankarHouse)
export const saveMojazPayankarHouse = createPostRequest(endpoints.SC.saveMojazPayankarHouse)
export const getMojazPayankarBuilding = createPostRequest(endpoints.SC.getMojazPayankarBuilding)
export const getMojazPayankarApartment = createPostRequest('/GetMojazPayankar_Apartment')
export const SaveMojazPayankarApartment = createPostRequest('/SaveMojazPayankar_Apartment')
export const saveMojazPayankarBuilding = createPostRequest(endpoints.SC.saveMojazPayankarBuilding)
export const getMojazMovafeghatOsooliHouse = createPostRequest(endpoints.SC.getMojazMovafeghatOsooliHouse)
export const saveMojazMovafeghatOsooliHouse = createPostRequest(endpoints.SC.saveMojazMovafeghatOsooliHouse)
export const tajmi = createPostRequest(endpoints.SC.tajmi)
export const tafkik = createPostRequest(endpoints.SC.tafkik)
export const convertApartmentToHouse = createPostRequest(endpoints.SC.convertApartmentToHouse)
export const convertHouseSharingToBuilding = createPostRequest(endpoints.SC.convertHouseSharingToBuilding)
export const convertHouseToHouseSharing = createPostRequest(endpoints.SC.convertHouseToHouseSharing)
export const ConvertBuildingToHouseSharing = createPostRequest(endpoints.SC.ConvertBuildingToHouseSharing)
export const copyHistoryToMapControl = createPostRequest(endpoints.SC.copyHistoryToMapControl)
export const getMomayeziConnectToParvandehList = createPostRequest(endpoints.SC.getMomayeziConnectToParvandehList)
export const connectParvandehToMomayezi = createPostRequest(endpoints.SC.connectParvandehToMomayezi)
export const getContrastBuilding = createPostRequest(endpoints.SC.getContrastBuilding)
export const loadCommunication = createPostRequest(endpoints.SC.loadCommunication)
export const saveCommunication = createPostRequest(endpoints.SC.saveCommunication)
export const loadParvandehJob = createPostRequest(endpoints.SC.loadParvandehJob)
export const loadMomayeziJob = createPostRequest(endpoints.SC.loadMomayeziJob)
export const saveParvandehJob = createPostRequest(endpoints.SC.saveParvandehJob)
export const deleteParvandehJob = createPostRequest(endpoints.SC.deleteParvandehJob)
export const CancelTajmi = createPostRequest(endpoints.SC.CancelTajmi)
export const getGarbageKartabl = createPostRequest(endpoints.SC.getGarbageKartabl)
export const disconnectParvandehAndMomayezi = createPostRequest(endpoints.SC.disconnectParvandehAndMomayezi)
export const getJobNameDetails = createPostRequest(endpoints.SC.getJobNameDetails)
export const copyMomayeziBaseInfoToParvandeh = createPostRequest(endpoints.SC.copyMomayeziBaseInfoToParvandeh)
export const getCodeInfoForNosazi = createPostRequest(endpoints.SC.getCodeInfoForNosazi)
export const getPayOffYear = createPostRequest(endpoints.SC.getPayOffYear)
export const setPayOffyear = createPostRequest(endpoints.SC.setPayOffyear)
export const addNosaziCodeFromMomayeziInParvandeh = createPostRequest(endpoints.SC.addNosaziCodeFromMomayeziInParvandeh)
export const transferAllNosaziCode = createPostRequest(endpoints.SC.transferAllNosaziCode)
export const getContrastMomayeziParvandehInfo = createPostRequest(endpoints.SC.getContrastMomayeziParvandehInfo)
export const getShApartmentEarlySoldList = createPostRequest(endpoints.SC.getShApartmentEarlySoldList)
export const saveBarokaf = createPostRequest(endpoints.SC.saveBarokaf)
export const loadLetterInNidNosaziCode = createPostRequest(endpoints.SC.loadLetterInNidNosaziCode)
export const loadLetter = createPostRequest(endpoints.SC.loadLetter)
export const saveLetterInNidNosaziCode = createPostRequest(endpoints.SC.saveLetterInNidNosaziCode)
export const saveLetter = createPostRequest(endpoints.SC.saveLetter)
export const calculateZabetehChidemanAndSave = createPostRequest(endpoints.SC.calculateZabetehChidemanAndSave)
export const copyToMovafeghatOsooli = createPostRequest(endpoints.SC.copyToMovafeghatOsooli)
export const saveZabetehChideman = createPostRequest(endpoints.SC.saveZabetehChideman)
export const savePlanOrder = createPostRequest(endpoints.SC.savePlanOrder)
export const loadCommitmentInNidNosaziCode = createPostRequest(endpoints.SC.loadCommitmentInNidNosaziCode)
export const loadCommitment = createPostRequest(endpoints.SC.loadCommitment)
export const saveCommitment = createPostRequest(endpoints.SC.saveCommitment)
export const loadMokatebatConfirm = createPostRequest(endpoints.SC.loadMokatebatConfirm)
export const getAccountingDocNotSentList = createPostRequest(endpoints.SC.getAccountingDocNotSentList)
export const resendFichesToFinanceSystem = createPostRequest(endpoints.SC.resendFichesToFinanceSystem)
export const saveMokatebatConfirm = createPostRequest(endpoints.SC.saveMokatebatConfirm)
export const getStaffInfo = createPostRequest(endpoints.SC.getStaffInfo)
export const saveStaffInfo = createPostRequest(endpoints.SC.saveStaffInfo)
export const deleteStaffInfo = createPostRequest(endpoints.SC.deleteStaffInfo)
export const loadManagerConfirm = createPostRequest(endpoints.SC.loadManagerConfirm)
export const getCiResourceManagerConfirmDetailsFromCiResourceManagerConfirm = createPostRequest(endpoints.SC.getCiResourceManagerConfirmDetailsFromCiResourceManagerConfirm)
export const saveManagerConfirm = createPostRequest(endpoints.SC.saveManagerConfirm)
export const loadElevator = createPostRequest(endpoints.SC.loadElevator)
export const saveElevator = createPostRequest(endpoints.SC.saveElevator)
export const getAllAsansor = createPostRequest("GetAllAsansor")
export const revokeElevator = createPostRequest(endpoints.SC.revokeElevator)
export const getAllDiscountList = createPostRequest(endpoints.SC.getAllDiscountList)
export const saveAllDiscount = createPostRequest(endpoints.SC.saveAllDiscount)

// Revisit
export const copyRevisitToRevisit = createPostRequest(endpoints.SC.copyRevisitToRevisit)
export const copyParvandehToRevisit = createPostRequest(endpoints.SC.copyParvandehToRevisit)
export const getRevisitHouse = createPostRequest(endpoints.SC.getRevisitHouse)
export const saveRevisitHouse = createPostRequest(endpoints.SC.saveRevisitHouse)
export const getRevisitBuilding = createPostRequest(endpoints.SC.getRevisitBuilding)
export const saveRevisitBuilding = createPostRequest(endpoints.SC.saveRevisitBuilding)
export const getRevisitApartment = createPostRequest(endpoints.SC.getRevisitApartment)
export const saveRevisitApartment = createPostRequest(endpoints.SC.saveRevisitApartment)
export const saveRevisitApartmentParvandeh = createPostRequest(endpoints.SC.saveRevisitApartmentParvandeh)
export const saveRevisitHouseParvande = createPostRequest(endpoints.SC.saveRevisitHouseParvande)
export const saveRevisitHouseSharingParvandeh = createPostRequest(endpoints.SC.saveRevisitHouseSharingParvandeh)
export const getRevisitHouseSharing = createPostRequest(endpoints.SC.getRevisitHouseSharing)
export const saveRevisitHouseSharing = createPostRequest(endpoints.SC.saveRevisitHouseSharing)
export const getRevisitShop = createPostRequest(endpoints.SC.getRevisitShop)
export const saveRevisitShop = createPostRequest(endpoints.SC.saveRevisitShop)
export const loadRevisitJob = createPostRequest(endpoints.SC.loadRevisitJob)
export const saveRevisitJob = createPostRequest(endpoints.SC.saveRevisitJob)
export const getRevisitAgentList = createPostRequest(endpoints.SC.getRevisitAgentList)
export const saveRevisitAgent = createPostRequest(endpoints.SC.saveRevisitAgent)
export const deleteRevisitAgent = createPostRequest(endpoints.SC.deleteRevisitAgent)
export const getShRevisitAgentListForAssign = createPostRequest(endpoints.SC.getShRevisitAgentListForAssign)
export const getRevisitAgentVacation = createPostRequest(endpoints.SC.getRevisitAgentVacation)
export const saveRevisitAgentVacation = createPostRequest(endpoints.SC.saveRevisitAgentVacation)
export const getRevisitAgentAssignGroup = createPostRequest(endpoints.SC.getRevisitAgentAssignGroup)
export const getRevisitAgentAssignInOneDay = createPostRequest(endpoints.SC.getRevisitAgentAssignInOneDay)
export const getAllRevisitAgentList = createPostRequest(endpoints.SC.getAllRevisitAgentList)
export const addAssignRevisit = createPostRequest(endpoints.SC.addAssignRevisit)
export const activeRevisitForRequest = createPostRequest(endpoints.SC.activeRevisitForRequest)
export const deleteRevisit = createPostRequest(endpoints.SC.deleteRevisit)
export const copyFromMojazParvanehToRevisit = createPostRequest(endpoints.SC.copyFromMojazParvanehToRevisit)
export const copyFromMojazPayankarToRevisit = createPostRequest(endpoints.SC.copyFromMojazPayankarToRevisit)
export const loadZabetehChidemanHistory = createPostRequest(endpoints.SC.loadZabetehChidemanHistory)

// History and search
export const getResponserKartabl = createPostRequest(endpoints.SC.getResponserKartabl)
export const getOutputList = createPostRequest(endpoints.SC.getOutputList)
export const getTemporaryKartablHistory = createPostRequest(endpoints.SC.getTemporaryKartablHistory)

// Duty
export const getDutyFiches = createPostRequest(endpoints.SC.getDutyFiches)
export const getDutyFicheSubs = createPostRequest(endpoints.SC.getDutyFicheSubs)
export const getShopCodeInfo = createPostRequest(endpoints.SC.getShopCodeInfo)

// Analysis
export const loadAnalysisBuildingListWithHistory = createPostRequest(endpoints.SC.loadAnalysisBuildingListWithHistory)
export const loadAnalysisBuilding = createPostRequest(endpoints.SC.loadAnalysisBuilding)
export const saveAnalysisBuilding = createPostRequest(endpoints.SC.saveAnalysisBuilding)
export const deleteAnalysisBuilding = createPostRequest(endpoints.SC.deleteAnalysisBuilding)
export const copyAnalysisBuilding = createPostRequest(endpoints.SC.copyAnalysisBuilding)
export const calculateAnalysisBuilding = createPostRequest(endpoints.SC.calculateAnalysisBuilding)
export const calculateAnalysisBuildingAndSave = createPostRequest(endpoints.SC.calculateAnalysisBuildingAndSave)

// Commission
export const getCommissionListInNidNosaziCode = createPostRequest(endpoints.SC.getCommissionListInNidNosaziCode)
export const loadCommission = createPostRequest(endpoints.SC.loadCommission)

// blackList
export const validationExitFromBlackList = createPostRequest(endpoints.SC.validationExitFromBlackList)

export const getTechnicalCommittee = createPostRequest(endpoints.SC.getTechnicalCommittee)
export const saveTechnicalCommittee = createPostRequest(endpoints.SC.saveTechnicalCommittee)
export const deleteUniversalOddmentAcount = createPostRequest(endpoints.SC.deleteUniversalOddmentAcount)
export const saveUniversalOddmentAcount = createPostRequest(endpoints.SC.saveUniversalOddmentAcount)
export const loadFireFightingLog = createPostRequest(endpoints.SC.loadFireFightingLog)
export const saveFireFighting = createPostRequest(endpoints.SC.saveFireFighting)
export const getParcel = createPostRequest(endpoints.SC.getParcel)
export const loadAllDiscountNationalCode = createPostRequest(endpoints.SC.loadAllDiscountNationalCode)
export const loadPlan = createPostRequest(endpoints.SC.loadPlan)
export const savePlan = createPostRequest(endpoints.SC.savePlan)

// arhicve
export const getTemporaryKartabl = createPostRequest(endpoints.SC.getTemporaryKartabl)
export const backFromTemporaryKartabl = createPostRequest(endpoints.SC.backFromTemporaryKartabl)
export const sendToTemporaryKartabl = createPostRequest(endpoints.SC.sendToTemporaryKartabl)
export const changeProcStatus = createPostRequest(endpoints.SC.changeProcStatus)
export const getAllListArchiveTemporaryShahrsazi = createPostRequest(endpoints.SC.getAllListArchiveTemporaryShahrsazi)
export const getPermanentKartabl = createPostRequest(endpoints.SC.getPermanentKartabl)
export const getPrintRequest = createPostRequest(endpoints.SC.getPrintRequest)
export const printRequest = createPostRequest(endpoints.SC.printRequest)
export const saveDiscountNationalCode = createPostRequest(endpoints.SC.saveDiscountNationalCode)
export const getCrossRequestByNidWorkitem = createPostRequest(endpoints.SC.getCrossRequestByNidWorkitem)
export const saveMapControl = createPostRequest(endpoints.SC.saveMapControl)

export const getEngineerInfoList = createPostRequest(endpoints.SC.getEngineerInfoList)
export const saveEngineerInfo = createPostRequest(endpoints.SC.saveEngineerInfo)
export const getBaseNidActionList = createPostRequest(endpoints.SC.getBaseNidActionList)

// commission
export const getCommissionListInNidProc = createPostRequest(endpoints.SC.getCommissionListInNidProc)
export const saveCommission = createPostRequest(endpoints.SC.saveCommission)
export const getCICommissionAttachmentFromCICommissionType = createPostRequest(endpoints.SC.getCICommissionAttachmentFromCICommissionType)
export const cancelCommission = createPostRequest(endpoints.SC.cancelCommission)
export const loadFine = createPostRequest(endpoints.SC.loadFine)
export const saveFine = createPostRequest(endpoints.SC.saveFine)
export const calculateFine = createPostRequest(endpoints.SC.calculateFine)
export const calculateAndSaveFine = createPostRequest(endpoints.SC.calculateAndSaveFine)
export const checkIsConfirmOutput = createPostRequest(endpoints.SC.checkIsConfirmOutput)
export const loadInquiryResponse = createPostRequest(endpoints.SC.loadInquiryResponse)
export const saveInquiryResponse = createPostRequest(endpoints.SC.saveInquiryResponse)
export const getParkingStaff = createPostRequest('/GetParkingStaff')
export const saveParkingStaff = createPostRequest(endpoints.SC.saveParkingStaff)
export const deleteParkingStaff = createPostRequest(endpoints.SC.deleteParkingStaff)
export const getCrossRequest = createPostRequest('/GetCrossRequest')
export const saveCrossRequest = createPostRequest('/SaveCrossRequest')

export const confirmParkingStaff = createPostRequest('/ConfirmParkingStaff')
export const getMojazPayankarShop = createPostRequest('/GetMojazPayankar_Shop')
export const saveMojazPayankarShop = createPostRequest('/SaveMojazPayankar_Shop')
export const getMojazPayankarHouseSharing = createPostRequest('/GetMojazPayankar_HouseSharing')
export const saveMojazPayankarHouseSharing = createPostRequest('/SaveMojazPayankar_HouseSharing')
export const saveParkingStaffDetailes = createPostRequest(endpoints.SC.saveParkingStaffDetailes)
export const getParkingStaffDetailes = createPostRequest(endpoints.SC.getParkingStaffDetailes)
export const getCommissionExecVote = createPostRequest(endpoints.SC.getCommissionExecVote)
export const getUGPFormsConfirmation = createPostRequest(endpoints.SC.getUGPFormsConfirmation)
export const getEstateControlHistory = createPostRequest(endpoints.SC.getEstateControlHistory)
export const saveCommissionExecVote = createPostRequest(endpoints.SC.saveCommissionExecVote)
export const loadFoul = createPostRequest(endpoints.SC.loadFoul)
export const saveFoul = createPostRequest(endpoints.SC.saveFoul)
export const getShRequestSec = createPostRequest(endpoints.SC.getShRequestSec)
export const saveSecretariatDate = createPostRequest(endpoints.SC.saveSecretariatDate)
export const saveMafasaComments = createPostRequest(endpoints.SC.saveMafasaComments)
export const saveMissFoul = createPostRequest(endpoints.SC.saveMissFoul)
export const saveParvaneh = createPostRequest(endpoints.SC.saveParvaneh)

export const getUniversalOddmentAcount = createPostRequest(endpoints.SC.getUniversalOddmentAcount)
export const tashkilParvandeCopy = createPostRequest(endpoints.SC.tashkilParvandeCopy)
export const loadAllDiscount = createPostRequest(endpoints.SC.loadAllDiscount)
export const getSMSNumber = createPostRequest(endpoints.SC.getSMSNumber)
export const saveShShenasnameFani = createPostRequest(endpoints.SC.saveShShenasnameFani)
export const getShShenasnameFani = createPostRequest(endpoints.SC.getShShenasnameFani)
export const sendToBackKartabl = createPostRequest(endpoints.SC.sendToBackKartabl)
export const getConfirmationObjList = createPostRequest(endpoints.SC.getConfirmationObjList)
export const getShParkingStaffList = createPostRequest(endpoints.SC.getShParkingStaffList)
export const getTechnicalStaff = createPostRequest(endpoints.SC.getTechnicalStaff)
export const confirmTechnicalStaff = createPostRequest(endpoints.SC.confirmTechnicalStaff)
export const revokeOutput = createPostRequest(endpoints.SC.revokeOutput)
export const getParvandehHouseDeleted = createPostRequest(endpoints.SC.getParvandehHouseDeleted)
export const deleteAllDiscount = createPostRequest(endpoints.SC.deleteAllDiscount)
export const getActiveRequestList = createPostRequest(endpoints.SC.getActiveRequestList)
export const getShPeaceListWithHistory = createPostRequest(endpoints.SC.getShPeaceListWithHistory)
export const loadOnePeaceFromList = createPostRequest(endpoints.SC.loadOnePeaceFromList)
export const saveOnePeaceFromList = createPostRequest(endpoints.SC.saveOnePeaceFromList)
export const calculateOnePeaceFromList = createPostRequest(endpoints.SC.calculateOnePeaceFromList)
export const loadOneAgreementFromList = createPostRequest(endpoints.SC.loadOneAgreementFromList)
export const loadZabetehListWithHistory = createPostRequest(endpoints.SC.loadZabetehListWithHistory)
export const createNewZabeteh = createPostRequest(endpoints.SC.createNewZabeteh)
export const loadZabetehWithChideman = createPostRequest(endpoints.SC.loadZabetehWithChideman)
export const changeNosaziCodeInBlock = createPostRequest(endpoints.SC.changeNosaziCodeInBlock)
export const loadCommissionOrder = createPostRequest(endpoints.SC.loadCommissionOrder)
export const saveCommissionOrder = createPostRequest(endpoints.SC.saveCommissionOrder)
export const getDwgWrapperList = createPostRequest(endpoints.SC.getDwgWrapperList)
export const saveDwgWrapper = createPostRequest(endpoints.SC.saveDwgWrapper)
export const editDwgWrapper = createPostRequest(endpoints.SC.editDwgWrapper)
export const loadTafkikPieces = createPostRequest(endpoints.SC.loadTafkikPieces)
export const saveTafkikPieces = createPostRequest(endpoints.SC.saveTafkikPieces)
export const saveZabeteh = createPostRequest(endpoints.SC.saveZabeteh)
export const calculateZabetehAndSaveAndZabetehChideman = createPostRequest(endpoints.SC.calculateZabetehAndSaveAndZabetehChideman)
export const calculateZabeteh = createPostRequest(endpoints.SC.calculateZabeteh)
export const deleteZabeteh = createPostRequest(endpoints.SC.deleteZabeteh)
export const loadZabeteStatic = createPostRequest(endpoints.SC.loadZabeteStatic)
export const saveZabetehStatic = createPostRequest(endpoints.SC.saveZabetehStatic)
export const getApartmentEarlySold = createPostRequest(endpoints.SC.getApartmentEarlySold)
export const saveApartmentEarlySold = createPostRequest(endpoints.SC.saveApartmentEarlySold)
export const checkIsConfirmApartmentEarlySold = createPostRequest(endpoints.SC.checkIsConfirmApartmentEarlySold)
export const confirmApartmentEarlySold = createPostRequest(endpoints.SC.confirmApartmentEarlySold)
export const getShAgreementListWithHistory = createPostRequest(endpoints.SC.getShAgreementListWithHistory)
export const saveOneAgreementFromList = createPostRequest(endpoints.SC.saveOneAgreementFromList)
export const calculateOneAgreementFromList = createPostRequest(endpoints.SC.calculateOneAgreementFromList)
export const loadTechnicalStaff = createPostRequest(endpoints.SC.loadTechnicalStaff)
export const saveTechnicalStaff = createPostRequest(endpoints.SC.saveTechnicalStaff)
export const getCheckGarbageKartabl = createPostRequest(endpoints.SC.getCheckGarbageKartabl)
export const sendToGarbageKartabl = createPostRequest(endpoints.SC.sendToGarbageKartabl)
export const getTaskMobileForInvalidImages = createPostRequest(endpoints.SC.getTaskMobileForInvalidImages)
export const addMobileTaskForInvalidImages = createPostRequest(endpoints.SC.addMobileTaskForInvalidImages)
export const getShOfficeLetter = createPostRequest(endpoints.SC.getShOfficeLetter)
export const saveShOfficeLetter = createPostRequest(endpoints.SC.saveShOfficeLetter)
export const loadShcheckList = createPostRequest(endpoints.SC.loadShcheckList)
export const saveShcheckList = createPostRequest(endpoints.SC.saveShcheckList)
export const confirmShCheckList = createPostRequest(endpoints.SC.confirmShCheckList)
export const confirmShCommitmentCitizen = createPostRequest(endpoints.SC.confirmShCommitmentCitizen)
export const getShImageDetailsList = createPostRequest(endpoints.SC.getShImageDetailsList)
export const loadOneMovafeghatOsooliFromList = createPostRequest(endpoints.SC.loadOneMovafeghatOsooliFromList)
export const saveOneMovafeghatOsooliFromList = createPostRequest(endpoints.SC.saveOneMovafeghatOsooliFromList)

export const isConfirmMokatebat = createPostRequest('/IsConfirmMokatebat')
export const exportLetterOnArchiveAndMokatebat = createPostRequest('/ExportLetterOnArchiveAndMokatebat')

export const copyMovafeghatOsooli = createPostRequest('/CopyMovafeghatOsooli')

export const copyToLastRowMovafeghatOsooli = createPostRequest('/CopyToLastRowMovafeghatOsooli')

export const getShMovafeghatOsooliList = createPostRequest('/GetSh_MovafeghatOsooli_List')
export const CopyFromMojazPayankarToParvandeh = createPostRequest('/CopyFromMojazPayankarToParvandeh')

export const copyDataInParvandehInfo = createPostRequest('/Copy')
export const GetDrillingRig = createPostRequest('/GetDrillingRig')
export const SaveDrillingRig = createPostRequest('/SaveDrillingRig')

export const getEstateControl = createPostRequest('/GetEstateControl')
export const getIncomeFicheSub = createPostRequest('/GetIncomeFicheSub')
export const changeNewCodeRequestStatus = createPostRequest('/ChangeNewCodeRequestStatus')
export const getUGPNewCodeRequest = createPostRequest('/GetUGP_NewCodeRequest')
// export const getEstateControlHistory =
//   createPostRequest('/GetEstateControlHistory')

export const getParvandehHouseInNosaziCode = createPostRequest('/GetParvandeh_House_InNosaziCode')

export const copyEstateControlHistoryToCurrentRequest = createPostRequest('/CopyEstateControl_HistoryToCurrentRequest')
export const copy = createPostRequest('/Copy')
export const mergeArchiveBizCode = createPostRequest('/MergeArchiveBizCode')
export const getBlockAreaStatus = createPostRequest('/GetBlockAreaStatus')
export const recoveryBlockAreaStatus = createPostRequest('/RecoveryBlockAreaStatus')
export const saveBlockAreaStatus = createPostRequest('/SaveBlockAreaStatus')
// عملکر مهندسین ناظر
export const loadMapControlEngineer = createPostRequest('/LoadMapControl_Engineer ')
export const saveMapControlEngineer = createPostRequest('/SaveMapControl_Engineer ')

export const saveEstateControl = createPostRequest('/SaveEstateControl')
export const getArchiveWrapperListByNidProc = createPostRequest('/GetArchive_Wrapper_List_ByNidProc')
export const calculateEngineer = createPostRequest('/CalculateEngineer')
export const getMobileNumber = createPostRequest('/GetMobileNumber')
export const getArchiveMergeHistory = createPostRequest('/GetArchiveMergeHistory')
export const getShCutTreeOwnRequestByNidWorkItem = createPostRequest('/GetSh_CutTreeOwnRequestByNidWorkItem')
export const saveShCutTreeOwnRequest = createPostRequest('/SaveSh_CutTreeOwnRequest')
export const inquiryShCutTreeOwnRequest = createPostRequest('/InquirySh_CutTreeOwnRequest')
export const isAnyCommisionInNosaziCode = createPostRequest('/IsAnyCommisionInNosaziCode')
export const saveCICommitmentCitizen = createPostRequest('/SaveCI_CommitmentCitizen ')
export const getCICommitmentCitizenById = createPostRequest('/GetCI_CommitmentCitizenById')
export const getAllCICommitmentCitizen = createPostRequest('/GetAllCI_CommitmentCitizen')
export const sendToGarbageKartablNew = createPostRequest('/SendToGarbageKartablNew')
export const getPlanBankTags = createPostRequest('/GetPlanBankTags')

export const copyFromBankPlan = createPostRequest('/CopyFromBankPlan')
export const updateRevisitTime = createPostRequest('/UpdateRevisitTime')
export const sendToPermanentKartabl = createPostRequest('/SendToPermanentKartabl')
export const sendToPermanentKartablNew = createPostRequest('/SendToPermanentKartablNew')
export const processRecirculationCutTreeOwn = createPostRequest('/ProcessRecirculationCutTreeOwn')
export const getRevisitAgentResponserKartabl = createPostRequest('/GetRevisitAgentResponserKartabl')
export const getUGPformsConfirmation = createPostRequest('/GetUGP_FormsConfirmation')
export const saveUGPFormsConfirmation = createPostRequest('/SaveUGP_FormsConfirmation')
export const getShRequestInfoByNewNosaziCode = createPostRequest('/GetSh_RequestInfoByNewNosaziCode')
export const getBaseParvandehInfo = createPostRequest('/GetBase_ParvandehInfo')
export const copyInfoToMapOrder = createPostRequest('/CopyInfoToMapOrder')
export const getPersonAuthentication = createPostRequest('/GetPersonAuthentication')
export const getNationalCodeInquiry = createPostRequest('/GetNationalCodeInquiry')
export const getReportParameters = createPostRequest('/GetReportParameters')
export const getAddressFromPostcode = createPostRequest('/GetAddressFromPostcode')
export const confirmDiscountDetails = createPostRequest('/Confirm_DiscountDetails')
export const getCISMSSendTxt = createPostRequest('/GetCI_SMSSendTxt')
export const getSMSBody = createPostRequest('/GetSMSBody')
export const saveMomayeziShop = createPostRequest('/SaveMomayezi_Shop')
export const copyFromMojazMovafeghatOsooliToOneOfMovafeghatOsooli = createPostRequest('/CopyFromMojazMovafeghatOsooliToOneOfMovafeghatOsooli')
export const copyFromParvandehToOneOfMovafeghatOsooli = createPostRequest('/CopyFromParvandehToOneOfMovafeghatOsooli')
export const getVerificationForAsnad = createPostRequest('GetVerificationForAsnad')
export const getProvinceCodesForAsnad = createPostRequest('GetProvinceCodesForAsnad')
export const getUnitCodesForAsnad = createPostRequest('GetUnitCodesForAsnad')
export const saveRequestInMashhadEstate = createPostRequest('SaveRequestInMashhadEstate')
export const inquireRequestInMashhadEstate = createPostRequest('InquireRequestInMashhadEstate')
export const getLogAmlak = createPostRequest('GetLog_Amlak')
export const saveLogAmlak = createPostRequest('GetLog_Amlak')

/*

function createPostRequest (url) {
  return function (
    data,
    { config, ...apiConfig } = { config: { District: 1 } }
  ) {
    const { District = 1 } = config
    // eslint-disable-next-line no-undef
    const baseUrl = window.getConfigValue('SC')[District]
    if (!baseUrl) {
      return Promise.reject(
        `آدرس سرویس SC برای منطقه ${District} تعریف نشده است(${{ url }})`
      )
    }
    // apiConfig.withCredentials = true
    return axios.post(appendUrls([baseUrl, '/json', url]), data, apiConfig)
  }
}
*/
