export default {
  Base_NosaziCode: {},
  Base_Owner: [],
  Base_Edge: [],
  Base_RegisterPlack: [],
  Base_Scuttle: [],
  Base_HouseInfo: {},
  Base_CommonEstate: {},
  Base_ShahrsaziArchive: [],
  Base_AddressInfo: {},
  Base_AddressInfo_House: {},

  Base_AddressPostCode: null,
  Base_ApartmentInfo: null,
  Base_Attachment: null,
  Base_Bezel: null,
  Base_BlockInfo: null,
  Base_BlockOrganize: null,
  Base_BlockPath: null,
  Base_BlockPathConstant: null,
  Base_BuildingInfo: null,
  Base_Commission77History: null,
  Base_CommissionHistory: null,
  Base_Commitment: null,
  Base_CommonEstate_House: null,
  Base_ControllerInfo: null,
  Base_CurrentUsing: null,
  Base_CutTrees: null,
  Base_Dig: null,
  Base_Door: null,
  Base_DutyExemption: null,
  Base_Estehfazi: null,
  Base_File: null,
  Base_Front: null,
  Base_Gap: null,
  Base_GreenSpace: null,
  Base_Info: null,
  Base_Info_House: null,
  Base_Installation: null,
  Base_JobInfo: null,
  Base_Letter: null,
  Base_MultiBuilding: null,
  Base_Neighbor: null,
  Base_NosaziCode_House: null,
  Base_OtherEquipment: null,
  Base_Parking: null,
  Base_ParkingLackInParkingGroup: null,
  Base_ParkingLackInPlan: null,
  Base_ParkingRequirement: null,
  Base_ParkingRequirementInDensity: null,
  Base_ParkingSupplyInParkingGroup: null,
  Base_ParkingSupplyInPlan: null,
  Base_PlanForWork: null,
  Base_PlanMojaz: null,
  Base_PlanMosavab: null,
  Base_PreCodeInfo: null,
  Base_RenovationPaymentHistory: null,
  Base_ResourceInfo: null,
  Base_ShahrsaziArchiveHouse: null,
  Base_SharingInfrastructure: null,
  Base_ShopInfo: null,
  Base_SubScription: null,
  Base_SupplyParking: null,
  Base_Using: null,
  Base_Using_Paging: null,
  Base_Wall: null,
  // ErrorResult: null,
  // IsForDeletedItems: false,
  // MapImage: '',
  // NidBase_Parvandeh_HouseOrDastgah: '',
  // NidProc: '',
  // Revisit_History: {},
  // Security_EncryptCode: '',
  // Security_RequestGuid: '',
  // Sh_FinancePrice: {},
  _nidBase: '',
  House_Buildings_Base_BuildingInfoList: null,
  House_Buildings_Base_FrontList: null,
  House_Buildings_Base_InstallationList: null,
  House_Buildings_Base_UsingList: null
}
