export default {

  'pNidFiches': {
    'guid': ''
  },
  'pTargetNidNosaziCode': '',
  'pFromNickNameNid': '',
  'pToNickNameNid': '',
  'pUserCode': '',
  'pUserName': '',
  'pDutyFiches': {
    'Duty_Fiche': {
      'BankConfirmPrice': '0',
      'BankConfirmationDate': null,
      'BankConfirmationTime': null,
      'BankFilePath': null,
      'BankPaymentDate': null,
      'BillID': '0',
      'CI_DutyFicheExportType': '0',
      'CanceledDate': null,
      'CanceledTime': null,
      'Comments': null,
      'ConfirmBankCode': null,
      'DeleteDate': null,
      'DeleteTime': null,
      'DeletedNidUser': null,
      'DeletedUserName': null,
      'DepositID': null,
      'EumDutyFicheStatus': '0',
      'EumDutyPaymentType': '0',
      'EumDutyType': '2',
      'EumFicheConfirmMethode': null,
      'ExportDate': '',
      'ExportTime': '',
      'ExportationNo': '',
      'FicheExportTypeValue': null,
      'FicheNo': '',
      'FromDate': '',
      'IsDeleted': 'false',
      'NidFiche': '',
      'NidOwner': null,
      'NidUserBankConfirmer': null,
      'NidUserCanceler': null,
      'NidUserConfirmer': null,
      'NidUserExporter': '',
      'OtherFields': '',
      'OwnerName': null,
      'PayablePrice': '',
      'PaymentBreakDate': '',
      'PaymentBreakDateReal': null,
      'PaymentDate': null,
      'PaymentID': '',
      'PaymentRahgiriCode': null,
      'PaymentReferenceNo': null,
      'PrintDate': null,
      'PrintNidUser': null,
      'PrintTime': null,
      'PrintUserName': null,
      'RefundLetterDate': null,
      'RefundLetterNo': null,
      'ToDate': '',
      'TotalPrice': '',
      'UserConfirmationDate': null,
      'UserConfirmationTime': null,
      'UserNameBankConfirmer': null,
      'UserNameCanceler': null,
      'UserNameConfirmer': null,
      'UserNameExporter': ''
    }
  }

}
