export default {
  GetCommissionInfoByNidProcAhkamResult: {
    ADP_Commission: null,
    Agent: null,
    AgentType: null,
    Agents: null,
    CICommission: null,
    CIRegion: null,
    CI_Commission: null,
    CI_CommissionType: null,
    CI_TreepassType: null,
    CI_VoteType: null,
    CheckExistVoteToArchiveByNidCommission: "false",
    CheckExistVoteToArchiveByReportName: "false",
    ClsChartRequestReport: null,
    ClsCommission_ApposeVote: {
      Commission_ApposeVote: {
        ApposeOutsideDeadline: null,
        ApposeVoteDate: null,
        ApposeVoteDesc: null,
        ApposeVoteNo: null,
        NidCommission: null,
        NidUApposeVote: "00000000-0000-0000-0000-000000000000"
      },
      Commission_ApposeVotes: null,
      ErrorResult: null
    },
    ClsCommission_BlankList: {
      Commission_BlackList: null,
      Commission_BlackLists: null,
      ErrorResult: {
        BizErrors: null,
        Requirements: null
      },
      ListNosaziCode: null,
      NosaziCode: "3-4-18-37-1-0-0"
    },
    ClsCommission_ExecutTrackingVote: {
      Commission_ExecutTrackingVote: {
        CI_StatusOwner: 3,
        NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
        NidExecuteTracking: "80ed920e-7d0e-4cfa-b54b-576af9a15d47"
      },
      Commission_ExecuteTracking: [
        {
          CI_ExecuteMainVote: 0,
          CI_ExecuteSubsidiaryVote: 0,
          ExecuteVoteComments: null,
          ExecuteVoteDate: null,
          ExecuteVoteDesc: null,
          ExecuteVoteValue: "0",
          NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
          NidCommission_ExecuteTracking: "f144ab38-9e3a-4721-8b11-63e49dbffdee",
          NidExecuteTracking: "80ed920e-7d0e-4cfa-b54b-576af9a15d47",
          NidVT: "5bb09504-1db7-4b64-8720-2f9928efdadb"
        },
        {
          CI_ExecuteMainVote: 0,
          CI_ExecuteSubsidiaryVote: 0,
          ExecuteVoteComments: null,
          ExecuteVoteDate: null,
          ExecuteVoteDesc: null,
          ExecuteVoteValue: "0",
          NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
          NidCommission_ExecuteTracking: "4273ed1a-f6ae-477d-bd28-72e9b1f00f7c",
          NidExecuteTracking: "80ed920e-7d0e-4cfa-b54b-576af9a15d47",
          NidVT: "eee39520-06f6-49c8-8474-bd79249b2565"
        }
      ],
      SrvGetVoteTrepasses: [
        {
          AgentComment: null,
          AgentName: null,
          AreaMojaz: null,
          AreaMojod: null,
          BuildingStep: null,
          BusyAreaMojaz: "60",
          BusyAreaMosavab: null,
          CI_Commission: 3,
          CI_CommissionType: 1,
          CI_Evaluation: 0,
          CI_Note: 0,
          CI_PrintType: 1,
          CI_SazeType: 0,
          CI_TrepassType_Group: null,
          CI_UsingGroup: 0,
          CI_UsingType: 0,
          CI_UsingTypeGroupMojaz: null,
          CI_UsingTypeMojaz: null,
          CI_VoteType: 3,
          CI_VoteTypeDetail: 100,
          CI_Years: 1400,
          CalculationPrice: "0.0",
          CommissionDate: "1401/10/11",
          DeadlineGhararVote: "0",
          DescriptionOfSystem: null,
          Floor: "1",
          FloorCountMojaz: "4",
          FloorCountMosavab: null,
          Id: "3019",
          IdOld: "3019",
          IncomeArea: "2",
          IsAmar: "false",
          IsHave: "0",
          IsNote7Action: "false",
          K: "50041250",
          KCoeffiecient: "3",
          MaxPenalty: "3",
          MinPenalty: "0.5",
          MojazUsingID: null,
          MojazUsingTitle: "مسكوني تراكم كم",
          MosavabUsingID: null,
          MosavabUsingTitle: "مسكوني تراكم كم",
          NidAgent: "96f93b01-74ab-4522-b19a-61e3a8e1bb72",
          NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
          NidTrepass: "eb14b67c-b958-42fb-8f1f-19c237593bd8",
          NidVT: "5bb09504-1db7-4b64-8720-2f9928efdadb",
          NidVote: "8faca2af-eaf6-45b3-b22a-927554fdc1a9",
          Note: null,
          NoteComment: null,
          P: "116375000",
          PenaltyFormula: null,
          SystemSuggestion: null,
          TarakomMojaz: "120.000",
          TarakomMosavab: null,
          TechnicalValue: "0",
          Title: "پيشروي طولي مازاد از 10%",
          TitleOld: "پيشروي طولي مازاد از 10%",
          TmpNidTrepass: null,
          TrepassStatus: "0",
          TrepassValue: "235",
          TrepassValueAmar: null,
          Trepass_Comments: null,
          UrbanIdia: "قلع بنا",
          UrbanNidKartablItem: "10120140",
          UsingGroupID: "11",
          UsingGroupTitle: "مسكوني",
          UsingID: "0",
          UsingTitle: null,
          UsingTypeTitle: null,
          VahedCountMojaz: null,
          VahedCountMosavab: null,
          VoteDate: "1402/01/06",
          VoteNo: "3/02/360158",
          VotePriority: "1",
          VoteValue: "0",
          VoteValueAmar: "0",
          Vote_Comments:
            "باتوجه به اينکه تخلف نامبرده برخلاف اصول فني و شهرسازي  (مغاير با مفاد پروانه- احداث بناي بدون پروانه ساختمان- احداثي در کاربري غيرمجاز- تجاوز به معابر شهري و عدم رعايت بر اصلاحي- احداث طبقه مازاد بر پروانه- تفکيک غيرمجاز) مي باشد، لذا مستنداً به تبصره 1 ماده صد قانون شهرداري رأي به قلع بنا ظرف مدت 14روز ازتاريخ ابلاغ رأي صادر مي گردد. تسسسسسسسسسسسسسسسسسسسسسسسسسسسست"
        },
        {
          AgentComment: null,
          AgentName: null,
          AreaMojaz: null,
          AreaMojod: null,
          BuildingStep: null,
          BusyAreaMojaz: "60",
          BusyAreaMosavab: null,
          CI_Commission: 3,
          CI_CommissionType: 1,
          CI_Evaluation: 0,
          CI_Note: 0,
          CI_PrintType: 1,
          CI_SazeType: 0,
          CI_TrepassType_Group: null,
          CI_UsingGroup: 0,
          CI_UsingType: 0,
          CI_UsingTypeGroupMojaz: null,
          CI_UsingTypeMojaz: null,
          CI_VoteType: 3,
          CI_VoteTypeDetail: 100,
          CI_Years: 1401,
          CalculationPrice: "0.0",
          CommissionDate: "1401/10/11",
          DeadlineGhararVote: "0",
          DescriptionOfSystem: null,
          Floor: "0",
          FloorCountMojaz: "4",
          FloorCountMosavab: null,
          Id: "3019",
          IdOld: "3019",
          IncomeArea: "2",
          IsAmar: "false",
          IsHave: "0",
          IsNote7Action: "false",
          K: "61678750",
          KCoeffiecient: "3",
          MaxPenalty: "3",
          MinPenalty: "0.5",
          MojazUsingID: null,
          MojazUsingTitle: "مسكوني تراكم كم",
          MosavabUsingID: null,
          MosavabUsingTitle: "مسكوني تراكم كم",
          NidAgent: "96f93b01-74ab-4522-b19a-61e3a8e1bb72",
          NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
          NidTrepass: "2abf2a56-9e9b-4aa7-ad33-c21e3abac7a8",
          NidVT: "eee39520-06f6-49c8-8474-bd79249b2565",
          NidVote: "8faca2af-eaf6-45b3-b22a-927554fdc1a9",
          Note: null,
          NoteComment: null,
          P: "116375000",
          PenaltyFormula: null,
          SystemSuggestion: null,
          TarakomMojaz: "120.000",
          TarakomMosavab: null,
          TechnicalValue: "0",
          Title: "پيشروي طولي مازاد از 10%",
          TitleOld: "پيشروي طولي مازاد از 10%",
          TmpNidTrepass: null,
          TrepassStatus: "0",
          TrepassValue: "1",
          TrepassValueAmar: null,
          Trepass_Comments: "خلاف جهت",
          UrbanIdia: "قلع بنا",
          UrbanNidKartablItem: "10120140",
          UsingGroupID: "11",
          UsingGroupTitle: "مسكوني",
          UsingID: "0",
          UsingTitle: null,
          UsingTypeTitle: null,
          VahedCountMojaz: null,
          VahedCountMosavab: null,
          VoteDate: "1402/01/06",
          VoteNo: "3/02/360158",
          VotePriority: "1",
          VoteValue: "0",
          VoteValueAmar: "0",
          Vote_Comments:
            "باتوجه به اينکه تخلف نامبرده برخلاف اصول فني و شهرسازي  (مغاير با مفاد پروانه- احداث بناي بدون پروانه ساختمان- احداثي در کاربري غيرمجاز- تجاوز به معابر شهري و عدم رعايت بر اصلاحي- احداث طبقه مازاد بر پروانه- تفکيک غيرمجاز) مي باشد، لذا مستنداً به تبصره 1 ماده صد قانون شهرداري رأي به قلع بنا ظرف مدت 14روز ازتاريخ ابلاغ رأي صادر مي گردد. تسسسسسسسسسسسسسسسسسسسسسسسسسسسست"
        }
      ]
    },
    ClsCommission_Impart: {
      Commission_Impart: {
        Desciption: null,
        ImpartDate: "1401/12/13",
        ImpartNo: "297640134500141810009182",
        LawyerOwnerMadeh68: null,
        NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
        NidImpart: "2ed4a84c-bd25-48c1-8472-b160b935b74a",
        NotificationagentName: "موذنی",
        OwnerNameMadeh68: null,
        OwnerNameMadeh69: null,
        OwnerNameMadeh70: null,
        OwnerNameMadeh75: null,
        OwnerNameMadeh76: null,
        SideNameMadeh69: null,
        SideNameMadeh75: null,
        SideNameMadeh76: null,
        TypeProcedure: "2",
        VoteReceiverCode: null,
        VoteReceiverName: null,
        VoteReceiverNo: null
      },
      Commission_Imparts: null,
      ErrorResult: null
    },
    ClsCommission_Info: null,
    ClsCommission_LegalProxy: {
      Commission_LegalProxy: {
        BizCode: null,
        CI_InTime: null,
        CancelDate: null,
        CancelTime: null,
        CancelUserId: null,
        CancelUserName: null,
        ConfirmDate: null,
        ConfirmTime: null,
        ConfirmUserId: null,
        ConfirmUserName: null,
        CreateDate: null,
        CreateTime: null,
        CreateUserId: null,
        Description: null,
        EntryCount: null,
        FileName: null,
        IsCancel: null,
        IsConfirm: null,
        IsRenewalConfirm: null,
        IsRenewalRequest: null,
        LetterDate: null,
        LetterNumber: null,
        NidCommission: "00000000-0000-0000-0000-000000000000",
        NidFile: null,
        NidLegalProxy: "00000000-0000-0000-0000-000000000000",
        NoticeDate: null,
        NoticeNumber: null,
        OrderDate: null,
        OrderNumber: null,
        RenewalConfirmCreateDate: null,
        RenewalConfirmCreateTime: null,
        RenewalConfirmDate: null,
        RenewalConfirmNumber: null,
        RenewalConfirmUserName: null,
        RenewalRequestCreateDate: null,
        RenewalRequestCreateTime: null,
        RenewalRequestDate: null,
        RenewalRequestNumber: null,
        RenewalUserName: null
      },
      Commission_LegalProxyExecutionOrders: null,
      Commission_LegalProxyExtensions: null,
      Rules: {
        CI_Ruling: [
          {
            ID: "1",
            IsChecked: "false",
            Title: "قلع"
          },
          {
            ID: "2",
            IsChecked: "false",
            Title: "تعطيل و تبديل"
          },
          {
            ID: "3",
            IsChecked: "false",
            Title: "گود خطري"
          },
          {
            ID: "4",
            IsChecked: "false",
            Title: "ساير"
          }
        ]
      }
    },
    ClsCommission_Proclamation: null,
    ClsGetAllTaskResponse: null,
    ClsTemporaryArchive: null,
    ClsTokens: {
      ClsToken: [
        {
          Name: "حسین فکور",
          NidAgent: "73278347-55c6-4315-b7b3-07b0a2e1989d",
          TokenID: "93.0.7.17"
        },
        {
          Name: "محمود عارفی",
          NidAgent: "e320f34c-9a62-40f8-8354-a578467b546e",
          TokenID: "93.0.7.45"
        },
        {
          Name: "سید ابراهیم علیزاده",
          NidAgent: "c80d701d-2fba-490f-89b9-0ff58c05d331",
          TokenID: "93.0.7.67"
        }
      ]
    },
    ClsTrepasses: null,
    CommissionAfter: null,
    CommissionFilter: null,
    CommissionInfo: {
      Address: "محرابخان-طلاب-خيابان طبرسي- پلاک ابي 992",
      AllUrbanComments: null,
      Apartment: "0",
      BackStateTitle: null,
      BillNo: null,
      Block: "18",
      Building: "1",
      CI_BoundCode: "0",
      CI_Commission: "3",
      CI_CommissionBroken: "0",
      CI_CommissionOld: null,
      CI_CommissionPriority: null,
      CI_CommissionType: "1",
      CI_PrintType: "1",
      CI_Region: "3",
      CI_RelapseType: null,
      CI_VoteCorrection: "0",
      CodeString: "3-4-18-37-1-0-0",
      ColorInKartabl: null,
      ComEnterDate: "1401/10/11",
      Comments: null,
      CommissionComments: null,
      CommissionDate: "1401/10/11",
      CommissionDateExpert: "1401/10/11",
      CommissionState: null,
      CurrentArea: "0",
      DateLicence: null,
      Density: null,
      District: "3",
      DocArea: null,
      DocTypeTitle: null,
      ExpertName: "سيما  پيرآزاد (pirazad)",
      HasComments: "false",
      HasLegalExpert: null,
      House: "37",
      IsManagementMustBehold: null,
      IsMeeting: "false",
      IsRandomCom: "false",
      IsRun: null,
      IsSara10: "true",
      IsVotable: "true",
      Iscomplainant: "false",
      LegalExpertComments: null,
      NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
      NidProc: "83999090-54be-4e5f-a2ff-8fb2b90c18a5",
      NidProcAhkam: "5ef46f15-d210-4a3d-b6b3-1f086202931b",
      NidTaskState: "b4a97f78-f820-44fe-bbc1-10becc8224e9",
      NoLicence: null,
      NoTownDabir: null,
      OwnerCellNo: "09107896823",
      OwnerName: "تست تست",
      OwnerNationalCode: null,
      OwnerTelNo: null,
      PenaltyValue: null,
      Pieces: null,
      PostCode: null,
      PreCode: null,
      RandomCommissionDate: "1401/10/11",
      Region: "4",
      Regplaque: null,
      RelapseComments: null,
      RelapseDate: null,
      RelapseTime: null,
      Remark: null,
      Requester: "جواد نقيبي (naghibi)",
      RootSubject: null,
      Run_Comments: null,
      SecretariatNo: "360158",
      Shop: "0",
      SubNo: null,
      SysCI_City: null,
      SysCI_RequestBy: "1",
      TmpNidFilKernel: null,
      TreeLevel: "3333930",
      UrbanComments: null,
      UrbanNidKartablItem: "10120140",
      UrbanNidRequest: null,
      UrbanRequestDate: null,
      UsingGroup_Mojood: null,
      UsingTypeTitle: null,
      VoterUserName: "علي نظري (nazari)",
      WorkflowTitel: "مفاصاحساب",
      X: null,
      Y: null
    },
    CommissionInfos: [
      {
        Address: "محرابخان-طلاب-خيابان طبرسي- پلاک ابي 992",
        AllUrbanComments: null,
        Apartment: "0",
        BackStateTitle: null,
        BillNo: null,
        Block: "18",
        Building: "1",
        CI_BoundCode: "0",
        CI_Commission: "3",
        CI_CommissionBroken: "0",
        CI_CommissionOld: null,
        CI_CommissionPriority: null,
        CI_CommissionType: "1",
        CI_PrintType: "1",
        CI_Region: "3",
        CI_RelapseType: null,
        CI_VoteCorrection: "0",
        CodeString: "3-4-18-37-1-0-0",
        ColorInKartabl: null,
        ComEnterDate: "1401/10/11",
        Comments: null,
        CommissionComments: null,
        CommissionDate: "1401/10/11",
        CommissionDateExpert: "1401/10/11",
        CommissionState: null,
        CurrentArea: "0",
        DateLicence: null,
        Density: null,
        District: "3",
        DocArea: null,
        DocTypeTitle: null,
        ExpertName: "سيما  پيرآزاد (pirazad)",
        HasComments: "false",
        HasLegalExpert: null,
        House: "37",
        IsManagementMustBehold: null,
        IsMeeting: "false",
        IsRandomCom: "false",
        IsRun: null,
        IsSara10: "true",
        IsVotable: "true",
        Iscomplainant: "false",
        LegalExpertComments: null,
        NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
        NidProc: "83999090-54be-4e5f-a2ff-8fb2b90c18a5",
        NidProcAhkam: "5ef46f15-d210-4a3d-b6b3-1f086202931b",
        NidTaskState: "b4a97f78-f820-44fe-bbc1-10becc8224e9",
        NoLicence: null,
        NoTownDabir: null,
        OwnerCellNo: "09107896823",
        OwnerName: "تست تست",
        OwnerNationalCode: null,
        OwnerTelNo: null,
        PenaltyValue: null,
        Pieces: null,
        PostCode: null,
        PreCode: null,
        RandomCommissionDate: "1401/10/11",
        Region: "4",
        Regplaque: null,
        RelapseComments: null,
        RelapseDate: null,
        RelapseTime: null,
        Remark: null,
        Requester: "جواد نقيبي (naghibi)",
        RootSubject: null,
        Run_Comments: null,
        SecretariatNo: "360158",
        Shop: "0",
        SubNo: null,
        SysCI_City: null,
        SysCI_RequestBy: "1",
        TmpNidFilKernel: null,
        TreeLevel: "3333930",
        UrbanComments: null,
        UrbanNidKartablItem: "10120140",
        UrbanNidRequest: null,
        UrbanRequestDate: null,
        UsingGroup_Mojood: null,
        UsingTypeTitle: null,
        VoterUserName: "علي نظري (nazari)",
        WorkflowTitel: "مفاصاحساب",
        X: null,
        Y: null
      }
    ],
    CommissionTrepasses: [
      {
        AreaMojaz: null,
        AreaMojod: null,
        BuildingStep: null,
        BusyAreaMojaz: "60",
        BusyAreaMosavab: null,
        CI_SazeType: "0",
        CI_TrepassType_Group: null,
        CI_UsingGroup: "0",
        CI_UsingType: "0",
        CI_UsingTypeGroupMojaz: null,
        CI_UsingTypeMojaz: null,
        CI_Years: "1400",
        CalculationPrice: "0.0",
        CommissionSarghofliValue: null,
        CreateDate: null,
        CreateTime: "10:08 AM",
        DescriptionOfSystem: null,
        Floor: "1",
        FloorCountMojaz: "4",
        FloorCountMosavab: null,
        Id: "3019",
        IdOld: "3019",
        IncomeArea: "2",
        IsComplainant: "false",
        IsPaid: "false",
        IsRightsBystanders: "false",
        K: "50041250",
        KCoeffiecient: "3",
        KCoeffiecientNote3: null,
        MaxPenalty: "3",
        MinPenalty: "0.5",
        MojazUsingID: null,
        MojazUsingTitle: "مسكوني تراكم كم",
        MosavabUsingID: null,
        MosavabUsingTitle: "مسكوني تراكم كم",
        NidAnalysisBuildingDetail: null,
        NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
        NidTrepass: "eb14b67c-b958-42fb-8f1f-19c237593bd8",
        Note: null,
        P: "116375000",
        PenaltyFormula: null,
        SuggestionCause: null,
        SystemSuggestion: null,
        TarakomMojaz: "120.000",
        TarakomMosavab: null,
        Title: "پيشروي طولي مازاد از 10%",
        TitleOld: "پيشروي طولي مازاد از 10%",
        TmpNidTrepass: null,
        TrepassStatus: "0",
        TrepassValue: "235",
        TrepassValueAmar: null,
        Trepass_Comments: null,
        TrespassDateHappendNotMelak: null,
        TrespassDateInEngineer: null,
        TrespassDateInMunicipality: "1400/05/05",
        UrbanIdia: "قلع بنا",
        UsingGroupID: "11",
        UsingGroupTitle: "مسكوني",
        UsingID: "0",
        UsingTitle: null,
        UsingTypeTitle: null,
        VahdatRavieh: null,
        VahedCountMojaz: null,
        VahedCountMosavab: null,
        ZaribVahdatRavieh: null
      },
      {
        AreaMojaz: null,
        AreaMojod: null,
        BuildingStep: null,
        BusyAreaMojaz: "60",
        BusyAreaMosavab: null,
        CI_SazeType: "0",
        CI_TrepassType_Group: null,
        CI_UsingGroup: "0",
        CI_UsingType: "0",
        CI_UsingTypeGroupMojaz: null,
        CI_UsingTypeMojaz: null,
        CI_Years: "1401",
        CalculationPrice: "0.0",
        CommissionSarghofliValue: null,
        CreateDate: null,
        CreateTime: "10:08 AM",
        DescriptionOfSystem: null,
        Floor: "0",
        FloorCountMojaz: "4",
        FloorCountMosavab: null,
        Id: "3019",
        IdOld: "3019",
        IncomeArea: "2",
        IsComplainant: "false",
        IsPaid: "false",
        IsRightsBystanders: "false",
        K: "61678750",
        KCoeffiecient: "3",
        KCoeffiecientNote3: null,
        MaxPenalty: "3",
        MinPenalty: "0.5",
        MojazUsingID: null,
        MojazUsingTitle: "مسكوني تراكم كم",
        MosavabUsingID: null,
        MosavabUsingTitle: "مسكوني تراكم كم",
        NidAnalysisBuildingDetail: null,
        NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
        NidTrepass: "2abf2a56-9e9b-4aa7-ad33-c21e3abac7a8",
        Note: null,
        P: "116375000",
        PenaltyFormula: null,
        SuggestionCause: null,
        SystemSuggestion: null,
        TarakomMojaz: "120.000",
        TarakomMosavab: null,
        Title: "پيشروي طولي مازاد از 10%",
        TitleOld: "پيشروي طولي مازاد از 10%",
        TmpNidTrepass: null,
        TrepassStatus: "0",
        TrepassValue: "1",
        TrepassValueAmar: null,
        Trepass_Comments: "خلاف جهت",
        TrespassDateHappendNotMelak: null,
        TrespassDateInEngineer: null,
        TrespassDateInMunicipality: "1401/03/01",
        UrbanIdia: "قلع بنا",
        UsingGroupID: "11",
        UsingGroupTitle: "مسكوني",
        UsingID: "0",
        UsingTitle: null,
        UsingTypeTitle: null,
        VahdatRavieh: null,
        VahedCountMojaz: null,
        VahedCountMosavab: null,
        ZaribVahdatRavieh: null
      }
    ],
    CommissionVoteOfAgent: null,
    CommissionVoteOfAgentAll: null,
    Commission_LegalProxyExecutionOrder: {
      AskedAuxiliaryForcesQuantity: null,
      AuxiliaryForcesDistricts: null,
      BizCode: null,
      CancelDate: null,
      CancelTime: null,
      CancelUserName: null,
      ConfirmDate: null,
      ConfirmTime: null,
      ConfirmUserName: null,
      Description: null,
      ExecutiveDistricts: null,
      FileName: null,
      IsCancel: null,
      IsConfirm: null,
      JudgeOrderDate: null,
      JudgeOrderNumber: null,
      NidFile: null,
      NidLegalProxyExecutionOrder: "00000000-0000-0000-0000-000000000000",
      NidLegalProxyExtension: "00000000-0000-0000-0000-000000000000",
      OperationCommand: null,
      OperationDate: null,
      OperationTime: null,
      PresentWomanForcesQuantity: null,
      SendedAuxiliaryForcesQuantity: null
    },
    Commission_LegalProxyExtension: {
      BizCode: null,
      CancelDate: null,
      CancelTime: null,
      CancelUserName: null,
      ConfirmDate: null,
      ConfirmTime: null,
      ConfirmUserName: null,
      CreateUserId: null,
      CreateUsername: null,
      Description: null,
      FileName: null,
      IsCancel: null,
      IsConfirm: null,
      LetterDate: null,
      LetterNumber: null,
      NidFile: null,
      NidLegalProxy: "00000000-0000-0000-0000-000000000000",
      NidLegalProxyExtension: "00000000-0000-0000-0000-000000000000",
      OrderDate: null,
      OrderNumber: null,
      Title: null,
      ValidFromDate: null,
      ValidTillDate: null
    },
    Commission_Relapse: null,
    DomainName: null,
    ExpertName: null,
    IsActive: "false",
    IsSara10: "false",
    ListCommissionVoteOfAgent: [
      {
        AcceptDate: "1402/01/06",
        AcceptTime: "12:09 PM",
        CI_AgentOpinion: "0",
        DeleteDate: null,
        DeleteTime: null,
        Description: ".",
        EnumStatusVoteAgent: null,
        IsAccept: "false",
        IsVoteOwner: "false",
        NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
        NidCommissionVoteOfAgent: "d1494f9c-c212-49a0-9ef2-d9f8f65b24d0",
        NidUser: "73278347-55c6-4315-b7b3-07b0a2e1989d",
        UserName: "حسين فکور"
      },
      {
        AcceptDate: "1402/01/06",
        AcceptTime: "12:09 PM",
        CI_AgentOpinion: "0",
        DeleteDate: null,
        DeleteTime: null,
        Description: ".",
        EnumStatusVoteAgent: null,
        IsAccept: "false",
        IsVoteOwner: "false",
        NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
        NidCommissionVoteOfAgent: "1192934f-c2d0-4ae8-a7dc-af084caf8510",
        NidUser: "c80d701d-2fba-490f-89b9-0ff58c05d331",
        UserName: "سيد ابراهيم عليزاده"
      },
      {
        AcceptDate: "1402/01/06",
        AcceptTime: "12:09 PM",
        CI_AgentOpinion: "0",
        DeleteDate: null,
        DeleteTime: null,
        Description: ".",
        EnumStatusVoteAgent: null,
        IsAccept: "false",
        IsVoteOwner: "false",
        NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
        NidCommissionVoteOfAgent: "1b2c88a2-5727-4364-933d-293c5016fb06",
        NidUser: "e320f34c-9a62-40f8-8354-a578467b546e",
        UserName: "محمود عارفي"
      }
    ],
    NIDCommission: "00000000-0000-0000-0000-000000000000",
    NIDVote: "00000000-0000-0000-0000-000000000000",
    NidProc: "00000000-0000-0000-0000-000000000000",
    NidProcAhkam: "00000000-0000-0000-0000-000000000000",
    OwnerCellNo: null,
    OwnerNationalCodeCommissionList: null,
    OwnerTelNo: null,
    ReferenceToLegalExpertList: null,
    ReportName: null,
    Requester: null,
    Token: null,
    Tokens: null,
    UserStates: null,
    AllBizCode: {
      Commission_Archive: {
        CI_ArchiveGroup: "4",
        Caption: "کميسيون",
        Domain: "Commission",
        NIdArchive: "99df0cff-fe59-4f28-8736-c14d7f3cdf22",
        NIdCommission: "3f958ae0-f159-46e1-9a47-01656ff9db3c",
        RootSubject: "F239A96E-A18F-46A8-A6E6-6F34CEBC5139"
      }
    },
    CI_Region: null,
    CI_Regions: [
      {
        ID: "0",
        ManagerName: null,
        Title: "نامشخص"
      },
      {
        ID: "1",
        ManagerName: "جناب آقاي مهندس نژاد حسين",
        Title: "منطقه یک"
      },
      {
        ID: "2",
        ManagerName: "جناب آقاي مهندس حسين پور",
        Title: "منطقه دو"
      },
      {
        ID: "3",
        ManagerName: "جناب آقاي مهندس خداشناس",
        Title: "منطقه سه"
      },
      {
        ID: "4",
        ManagerName: "جناب آقاي مهندس نعيمي مقدم",
        Title: "منطقه چهار"
      },
      {
        ID: "5",
        ManagerName: "جناب آقاي مهندس وحدتي پور",
        Title: "منطقه پنج"
      },
      {
        ID: "6",
        ManagerName: "جناب آقاي مهندس يزدانمهر",
        Title: "منطقه شش"
      },
      {
        ID: "7",
        ManagerName: "جناب آقاي مهندس برجسته نژاد",
        Title: "منطقه هفت"
      },
      {
        ID: "8",
        ManagerName: "جناب آقاي مهندس شريعتي",
        Title: "منطقه هشت"
      },
      {
        ID: "9",
        ManagerName: "جناب آقاي مهندس حسينقلي زاده مقدم",
        Title: "منطقه نه"
      },
      {
        ID: "10",
        ManagerName: "جناب آقاي مهندس اكبريان",
        Title: "منطقه ده"
      },
      {
        ID: "11",
        ManagerName: "جناب آقاي مهندس عرفانيان",
        Title: "منطقه یازده"
      },
      {
        ID: "12",
        ManagerName: "جناب آقاي مهندس شريعتمداري",
        Title: "منطقه دوازده"
      },
      {
        ID: "80",
        ManagerName: "جناب آقاي مهندس نورين مقدم",
        Title: "منطقه ثامن"
      }
    ],
    ClsSMS: null,
    CommissiomnAnalyze: null,
    CommissionCapacity: null,
    CommissionHoliday: null,
    CommissionStatus: "New",
    CommissionToken: null,
    CommissionTrepass_HistoryRelapse: null,
    CommissionVote: {
      AgentComment: null,
      CI_Evaluation: "0",
      CI_Note: "0",
      CI_VoteType: "3",
      CI_VoteTypeDetail: "100",
      DeadlineGhararVote: "0",
      DigitalSignature:
        "BBFXkQx+bJiIqILzgFzvlsIbd/EmCp3yK4Q3P5Jsd7AlxzdGq2vroBtnyiu8zDzTvFgIMm//XJTX0Ba8nvu6eDPZTO2XQaxypKqkC36oXpYTyUNPW8AJQLYrrZL71GJicky7B5CGHLQ=",
      IsHave: "0",
      IsNote7Action: "false",
      NidAgent: "96f93b01-74ab-4522-b19a-61e3a8e1bb72",
      NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
      NidVote: "8faca2af-eaf6-45b3-b22a-927554fdc1a9",
      NoteComment: null,
      TechnicalValue: "0",
      TmpNidVote: null,
      VoteDate: "1402/01/06",
      VoteNo: "3/02/360158",
      VotePriority: "1",
      VoteTime: "12:09:38",
      VoteValue: "0",
      VoteValueAmar: "0",
      Vote_Comments:
        "باتوجه به اينکه تخلف نامبرده برخلاف اصول فني و شهرسازي  (مغاير با مفاد پروانه- احداث بناي بدون پروانه ساختمان- احداثي در کاربري غيرمجاز- تجاوز به معابر شهري و عدم رعايت بر اصلاحي- احداث طبقه مازاد بر پروانه- تفکيک غيرمجاز) مي باشد، لذا مستنداً به تبصره 1 ماده صد قانون شهرداري رأي به قلع بنا ظرف مدت 14روز ازتاريخ ابلاغ رأي صادر مي گردد. تسسسسسسسسسسسسسسسسسسسسسسسسسسسست"
    },
    Commission_Agent_Signature: {
      Agent: [
        {
          CI_AgentType: 2,
          DigitalSignature: null,
          HandySignature: "",
          MobailNo: null,
          Name: "محمود عارفی",
          NidAgent: "e320f34c-9a62-40f8-8354-a578467b546e",
          SerialNo: "93.0.7.45",
          TmpAgentID: null
        },
        {
          CI_AgentType: 3,
          DigitalSignature: null,
          HandySignature: "",
          MobailNo: "09155029466",
          Name: "سید ابراهیم علیزاده",
          NidAgent: "c80d701d-2fba-490f-89b9-0ff58c05d331",
          SerialNo: "93.0.7.67",
          TmpAgentID: null
        },
        {
          CI_AgentType: 1,
          DigitalSignature: null,
          HandySignature: "",
          MobailNo: null,
          Name: "حسین فکور",
          NidAgent: "73278347-55c6-4315-b7b3-07b0a2e1989d",
          SerialNo: "93.0.7.17",
          TmpAgentID: null
        }
      ]
    },
    Commission_Appose: null,
    Commission_Archive: [
      {
        CI_ArchiveGroup: "4",
        Caption: "کميسيون",
        Domain: "Commission",
        NIdArchive: "2ddc06f0-c85d-480d-acf2-d7e8726ca4e9",
        NIdCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
        RootSubject: "F239A96E-A18F-46A8-A6E6-6F34CEBC5139"
      }
    ],
    Commission_CheckList: null,
    Commission_ConfirmVotes: null,
    Commission_Inquiry: null,
    Commission_PrintLog: null,
    Commission_VoteList: [
      {
        AgentComment: null,
        CI_Evaluation: 0,
        CI_Note: 0,
        CI_VoteType: 3,
        CI_VoteTypeDetail: 100,
        DeadlineGhararVote: "0",
        DigitalSignature:
          "BBFXkQx+bJiIqILzgFzvlsIbd/EmCp3yK4Q3P5Jsd7AlxzdGq2vroBtnyiu8zDzTvFgIMm//XJTX0Ba8nvu6eDPZTO2XQaxypKqkC36oXpYTyUNPW8AJQLYrrZL71GJicky7B5CGHLQ=",
        IsHave: "0",
        IsNote7Action: "false",
        NidAgent: "96f93b01-74ab-4522-b19a-61e3a8e1bb72",
        NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
        NidVote: "8faca2af-eaf6-45b3-b22a-927554fdc1a9",
        NoteComment: null,
        TechnicalValue: "0",
        TmpNidVote: null,
        VoteDate: "1402/01/06",
        VoteNo: "3/02/360158",
        VotePriority: "1",
        VoteTime: "12:09:38",
        VoteValue: "0",
        VoteValueAmar: "0",
        Vote_Comments:
          "باتوجه به اينکه تخلف نامبرده برخلاف اصول فني و شهرسازي  (مغاير با مفاد پروانه- احداث بناي بدون پروانه ساختمان- احداثي در کاربري غيرمجاز- تجاوز به معابر شهري و عدم رعايت بر اصلاحي- احداث طبقه مازاد بر پروانه- تفکيک غيرمجاز) مي باشد، لذا مستنداً به تبصره 1 ماده صد قانون شهرداري رأي به قلع بنا ظرف مدت 14روز ازتاريخ ابلاغ رأي صادر مي گردد. تسسسسسسسسسسسسسسسسسسسسسسسسسسسست"
      }
    ],
    Commission_VoteTrepasses: [
      {
        AgentComment: null,
        AgentName: null,
        AreaMojaz: null,
        AreaMojod: null,
        BuildingStep: null,
        BusyAreaMojaz: "60",
        BusyAreaMosavab: null,
        CI_Commission: 3,
        CI_CommissionType: 1,
        CI_Evaluation: 0,
        CI_Note: 0,
        CI_PrintType: 1,
        CI_SazeType: 0,
        CI_TrepassType_Group: null,
        CI_UsingGroup: 0,
        CI_UsingType: 0,
        CI_UsingTypeGroupMojaz: null,
        CI_UsingTypeMojaz: null,
        CI_VoteType: 3,
        CI_VoteTypeDetail: 100,
        CI_Years: 1400,
        CalculationPrice: "0.0",
        CommissionDate: "1401/10/11",
        DeadlineGhararVote: "0",
        DescriptionOfSystem: null,
        Floor: "1",
        FloorCountMojaz: "4",
        FloorCountMosavab: null,
        Id: "3019",
        IdOld: "3019",
        IncomeArea: "2",
        IsAmar: "false",
        IsHave: "0",
        IsNote7Action: "false",
        K: "50041250",
        KCoeffiecient: "3",
        MaxPenalty: "3",
        MinPenalty: "0.5",
        MojazUsingID: null,
        MojazUsingTitle: "مسكوني تراكم كم",
        MosavabUsingID: null,
        MosavabUsingTitle: "مسكوني تراكم كم",
        NidAgent: "96f93b01-74ab-4522-b19a-61e3a8e1bb72",
        NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
        NidTrepass: "eb14b67c-b958-42fb-8f1f-19c237593bd8",
        NidVT: "5bb09504-1db7-4b64-8720-2f9928efdadb",
        NidVote: "8faca2af-eaf6-45b3-b22a-927554fdc1a9",
        Note: null,
        NoteComment: null,
        P: "116375000",
        PenaltyFormula: null,
        SystemSuggestion: null,
        TarakomMojaz: "120.000",
        TarakomMosavab: null,
        TechnicalValue: "0",
        Title: "پيشروي طولي مازاد از 10%",
        TitleOld: "پيشروي طولي مازاد از 10%",
        TmpNidTrepass: null,
        TrepassStatus: "0",
        TrepassValue: "235",
        TrepassValueAmar: null,
        Trepass_Comments: null,
        UrbanIdia: "قلع بنا",
        UrbanNidKartablItem: "10120140",
        UsingGroupID: "11",
        UsingGroupTitle: "مسكوني",
        UsingID: "0",
        UsingTitle: null,
        UsingTypeTitle: null,
        VahedCountMojaz: null,
        VahedCountMosavab: null,
        VoteDate: "1402/01/06",
        VoteNo: "3/02/360158",
        VotePriority: "1",
        VoteValue: "0",
        VoteValueAmar: "0",
        Vote_Comments:
          "باتوجه به اينکه تخلف نامبرده برخلاف اصول فني و شهرسازي  (مغاير با مفاد پروانه- احداث بناي بدون پروانه ساختمان- احداثي در کاربري غيرمجاز- تجاوز به معابر شهري و عدم رعايت بر اصلاحي- احداث طبقه مازاد بر پروانه- تفکيک غيرمجاز) مي باشد، لذا مستنداً به تبصره 1 ماده صد قانون شهرداري رأي به قلع بنا ظرف مدت 14روز ازتاريخ ابلاغ رأي صادر مي گردد. تسسسسسسسسسسسسسسسسسسسسسسسسسسسست"
      },
      {
        AgentComment: null,
        AgentName: null,
        AreaMojaz: null,
        AreaMojod: null,
        BuildingStep: null,
        BusyAreaMojaz: "60",
        BusyAreaMosavab: null,
        CI_Commission: 3,
        CI_CommissionType: 1,
        CI_Evaluation: 0,
        CI_Note: 0,
        CI_PrintType: 1,
        CI_SazeType: 0,
        CI_TrepassType_Group: null,
        CI_UsingGroup: 0,
        CI_UsingType: 0,
        CI_UsingTypeGroupMojaz: null,
        CI_UsingTypeMojaz: null,
        CI_VoteType: 3,
        CI_VoteTypeDetail: 100,
        CI_Years: 1401,
        CalculationPrice: "0.0",
        CommissionDate: "1401/10/11",
        DeadlineGhararVote: "0",
        DescriptionOfSystem: null,
        Floor: "0",
        FloorCountMojaz: "4",
        FloorCountMosavab: null,
        Id: "3019",
        IdOld: "3019",
        IncomeArea: "2",
        IsAmar: "false",
        IsHave: "0",
        IsNote7Action: "false",
        K: "61678750",
        KCoeffiecient: "3",
        MaxPenalty: "3",
        MinPenalty: "0.5",
        MojazUsingID: null,
        MojazUsingTitle: "مسكوني تراكم كم",
        MosavabUsingID: null,
        MosavabUsingTitle: "مسكوني تراكم كم",
        NidAgent: "96f93b01-74ab-4522-b19a-61e3a8e1bb72",
        NidCommission: "557b5d7a-a514-4ce3-b1b5-338c055fd2c3",
        NidTrepass: "2abf2a56-9e9b-4aa7-ad33-c21e3abac7a8",
        NidVT: "eee39520-06f6-49c8-8474-bd79249b2565",
        NidVote: "8faca2af-eaf6-45b3-b22a-927554fdc1a9",
        Note: null,
        NoteComment: null,
        P: "116375000",
        PenaltyFormula: null,
        SystemSuggestion: null,
        TarakomMojaz: "120.000",
        TarakomMosavab: null,
        TechnicalValue: "0",
        Title: "پيشروي طولي مازاد از 10%",
        TitleOld: "پيشروي طولي مازاد از 10%",
        TmpNidTrepass: null,
        TrepassStatus: "0",
        TrepassValue: "1",
        TrepassValueAmar: null,
        Trepass_Comments: "خلاف جهت",
        UrbanIdia: "قلع بنا",
        UrbanNidKartablItem: "10120140",
        UsingGroupID: "11",
        UsingGroupTitle: "مسكوني",
        UsingID: "0",
        UsingTitle: null,
        UsingTypeTitle: null,
        VahedCountMojaz: null,
        VahedCountMosavab: null,
        VoteDate: "1402/01/06",
        VoteNo: "3/02/360158",
        VotePriority: "1",
        VoteValue: "0",
        VoteValueAmar: "0",
        Vote_Comments:
          "باتوجه به اينکه تخلف نامبرده برخلاف اصول فني و شهرسازي  (مغاير با مفاد پروانه- احداث بناي بدون پروانه ساختمان- احداثي در کاربري غيرمجاز- تجاوز به معابر شهري و عدم رعايت بر اصلاحي- احداث طبقه مازاد بر پروانه- تفکيک غيرمجاز) مي باشد، لذا مستنداً به تبصره 1 ماده صد قانون شهرداري رأي به قلع بنا ظرف مدت 14روز ازتاريخ ابلاغ رأي صادر مي گردد. تسسسسسسسسسسسسسسسسسسسسسسسسسسسست"
      }
    ],
    CurrentCity: null,
    ErrorResult: null,
    GetAgent: null,
    GetAllVotesAndTrepass: null,
    GraphResult: null,
    GraphVoteDate: null,
    IsMoghayerat: "false",
    MapDetails: null,
    PageInfo: null,
    PersianDateServer: "1402/05/29",
    PersianTimeServer: "PT14H41M25.9250783S",
    RandomCode: null,
    RegionAnalyze: null,
    Search: null,
    Status: null,
    TotalFiles: "0",
    TrepassAnalyze: null,
    UrbanDetails: null,
    UserInfo: null,
    ViolatorsAnalyze: null,
    WFHistory: null
  }
}
