export default {
  'Apartment': 0,
  'Block': 0,
  'Building': 0,
  'CI_City': 0,
  'District': 0,
  'EumBaseInfoGroup': 0,
  'EumNosaziCodeGroup': 0,
  'EumNosaziCodeObjType': 0,
  'EumRevisitGroup': 0,
  'House': 0,
  'Id': '',
  'IsRoot': false,
  'NidBase': '',
  'NidNosaziCode': '',
  'NidNosaziCodeParent': '',
  'NidRevisit': '',
  'NidUser': '',
  'ParentId': '',
  'Region': 0,
  'Shop': 0,
  'UserName': null
}
