this.commissionsKartablResult = [
  {
    'Address': null,
    'AgentCount': 0,
    'AgentName': null,
    'BackStateTitle': null,
    'BillNo': null,
    'BizCode': '1-4-76-10-1-2-0',
    'BizCodeMap': '1-4-76-10-1-2-0',
    'CI_BoundCode': 0,
    'CI_Commission': null,
    'CI_CommissionPriority': 0,
    'CI_CommissionType': 0,
    'CI_Region': 1,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': null,
    'Commission': null,
    'CommissionDate': '',
    'CommissionDateExpert': '',
    'CommissionState': 'Send',
    'CommissionType': null,
    'CompeletPrecent': 30,
    'DateCommissionExpert': '',
    'ExpertName': null,
    'GuidAgent': null,
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': false,
    'IsMeeting': false,
    'IsPast': false,
    'IsRelapse': false,
    'IsVote': -1,
    'LaterTime': 0,
    'LegalExpertComments': '',
    'NidCommission': '0444feef-fd95-4405-b5e3-fdb24111a938',
    'NidProc': '49f7b336-2c59-47c5-841b-fa0999039a19',
    'NidTask': '8393710a-28d0-45da-9bfe-95da0b0049e2',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': null,
    'OwnerName': 'مجید اسکویی',
    'OwnerNationalCode': null,
    'OwnerTelNo': null,
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '',
    'Regplaque': null,
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 140275,
    'SendDate': '',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کارشناسی',
    'UrbanNidRequest': 321617,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': null,
    'VoterUserName': '                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ',
    'WorkflowTitel': null,
    'X': null,
    'Y': null
  },
  {
    'Address': 'تجريش ',
    'AgentCount': 0,
    'AgentName': null,
    'BackStateTitle': null,
    'BillNo': null,
    'BizCode': '1-2-3957-1-1-1-0',
    'BizCodeMap': '1-2-3957-1-1-1-0',
    'CI_BoundCode': 0,
    'CI_Commission': null,
    'CI_CommissionPriority': 0,
    'CI_CommissionType': 1,
    'CI_Region': 1,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1400/04/15',
    'Commission': null,
    'CommissionDate': '1400/12/18',
    'CommissionDateExpert': '1400/09/29',
    'CommissionState': 'RandomCommission',
    'CommissionType': 'بدوي',
    'CompeletPrecent': 50,
    'DateCommissionExpert': '1400/12/18',
    'ExpertName': 'آذر توفيق نژاد (TofighnezhadAz)',
    'GuidAgent': null,
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': false,
    'IsRelapse': true,
    'IsVote': -1,
    'LaterTime': 249,
    'LegalExpertComments': '',
    'NidCommission': 'cc4d6184-d267-4ceb-8543-c4242ff608d7',
    'NidProc': 'cac8d85f-42aa-426b-99f9-8188c2a35997',
    'NidTask': '0793e947-e107-41f3-bda0-aac41ee6735d',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': '',
    'OwnerName': 'تست تست',
    'OwnerNationalCode': '',
    'OwnerTelNo': '',
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '',
    'Regplaque': '88888',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 140269,
    'SendDate': '1400/04/15',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون بندی تصادفی',
    'UrbanNidRequest': 289991,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': null,
    'VoterUserName': '                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ',
    'WorkflowTitel': 'پاسخ استعلام ادارات',
    'X': null,
    'Y': null
  },
  {
    'Address': 'تجريش',
    'AgentCount': 3,
    'AgentName': 'نماينده دادگستري | 1400/03/03  3:14 PM - نماينده شوراي شهر | 1400/03/03  3:14 PM - نماينده وزارت كشور | 1400/06/02  2:20 PM',
    'BackStateTitle': null,
    'BillNo': null,
    'BizCode': '1-5-88-330-2-0-0',
    'BizCodeMap': '1-5-88-330-2-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 1,
    'CI_CommissionPriority': 0,
    'CI_CommissionType': 1,
    'CI_Region': 1,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1398/10/12',
    'Commission': 'كميسيون يك',
    'CommissionDate': '1399/06/11',
    'CommissionDateExpert': '1399/11/30',
    'CommissionState': 'Commission1',
    'CommissionType': 'بدوي',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1399/06/11',
    'ExpertName': 'وحيد زاهد (ZahedV)',
    'GuidAgent': '44d8131a-edd8-4b24-a60f-579571ebb754 - 6ea84027-e8ad-4bf6-829f-641332fd8d9b - 8b7e86af-0172-4917-853b-4397c10356f9',
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': true,
    'IsRelapse': false,
    'IsVote': 4,
    'LaterTime': 800,
    'LegalExpertComments': '',
    'NidCommission': '7e84ad8d-558a-4998-adba-645e45379a25',
    'NidProc': '156a157c-26e2-4f76-adb3-0a6e5ba849bf',
    'NidTask': 'd60fd93e-8eb0-401a-8f92-c344b1ecbc18',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': '09121813344',
    'OwnerName': 'علی جلیله وند',
    'OwnerNationalCode': null,
    'OwnerTelNo': '09121813344',
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '',
    'Regplaque': '136-65-3',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 140241,
    'SendDate': '1398/10/12',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون1',
    'UrbanNidRequest': 287585,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': '1400/01/17',
    'VoterUserName': 'وحید زاهد (ZahedV)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ',
    'WorkflowTitel': 'پاسخ استعلام ادارات',
    'X': null,
    'Y': null
  },
  {
    'Address': 'چوبيندر خيابان شهدا نبش خيابان شهيد ابوالقاسمي',
    'AgentCount': 0,
    'AgentName': null,
    'BackStateTitle': null,
    'BillNo': null,
    'BizCode': '1-2-49-993-1-0-0',
    'BizCodeMap': '1-2-49-993-1-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 1,
    'CI_CommissionPriority': 0,
    'CI_CommissionType': 1,
    'CI_Region': 1,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1400/02/13',
    'Commission': 'كميسيون يك',
    'CommissionDate': '1400/08/03',
    'CommissionDateExpert': '1398/04/11',
    'CommissionState': 'Commission1',
    'CommissionType': 'بدوي',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1400/08/03',
    'ExpertName': 'عليرضا صالحي (SalehiA)',
    'GuidAgent': null,
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': true,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': false,
    'IsRelapse': false,
    'IsVote': -1,
    'LaterTime': 313,
    'LegalExpertComments': 'sc',
    'NidCommission': 'c1dbb99d-1163-42b7-91fa-2d9372776280',
    'NidProc': 'cfe2ec85-772b-4e9a-a82f-bc6bd1bbea04',
    'NidTask': 'd60fd93e-8eb0-401a-8f92-c344b1ecbc18',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': '',
    'OwnerName': 'سید قوام سید ابوالقاسمی',
    'OwnerNationalCode': null,
    'OwnerTelNo': '',
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '1397/04/09',
    'Regplaque': 'اصلی(6) - فرعی() - قطعه()',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 140189,
    'SendDate': '1400/02/13',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون1',
    'UrbanNidRequest': 228330,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': null,
    'VoterUserName': '                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ',
    'WorkflowTitel': null,
    'X': null,
    'Y': null
  },
  {
    'Address': 'خيابان راه اهن کوچه لطفيان کوچه  علي سياه  پلاک 15',
    'AgentCount': 1,
    'AgentName': 'نماينده وزارت كشور | 1400/12/17  3:37 PM',
    'BackStateTitle': 'ماده صد منطقه 1',
    'BillNo': null,
    'BizCode': '1-2-45-28-666-0-0',
    'BizCodeMap': '1-2-45-28-666-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 5,
    'CI_CommissionPriority': 1,
    'CI_CommissionType': 5,
    'CI_Region': 1,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1396/05/07',
    'Commission': 'كميسيون پنج',
    'CommissionDate': '1400/03/03',
    'CommissionDateExpert': '1398/01/24',
    'CommissionState': 'Commission5',
    'CommissionType': 'عدم پرداخت جريمه',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1400/03/03',
    'ExpertName': 'فائزه خردمندان (KheradmandanF)',
    'GuidAgent': '6ea84027-e8ad-4bf6-829f-641332fd8d9b',
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': true,
    'IsRelapse': false,
    'IsVote': 1,
    'LaterTime': 1687,
    'LegalExpertComments': '',
    'NidCommission': 'c8250b9f-ab58-4e69-9be8-94a60d38ae29',
    'NidProc': '71300a27-8e14-49d7-8aa4-31cbbcec3352',
    'NidTask': '92911c7a-2e1a-4f7d-9497-64ed37249e53',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': '',
    'OwnerName': 'حمید  هاشمی سیمیاری وشرکا',
    'OwnerNationalCode': null,
    'OwnerTelNo': '',
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '1400/02/11',
    'Regplaque': 'اصلی(2694) - فرعی(1) - قطعه()',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 140187,
    'SendDate': '1396/05/07',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون5',
    'UrbanNidRequest': 313170,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': '1399/04/29',
    'VoterUserName': 'علیرضا صالحی (SalehiA)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ',
    'WorkflowTitel': null,
    'X': null,
    'Y': null
  },
  {
    'Address': 'شهرک شهيد رجايي',
    'AgentCount': 0,
    'AgentName': null,
    'BackStateTitle': 'تست',
    'BillNo': null,
    'BizCode': '1-4-103-740-1-0-0',
    'BizCodeMap': '1-4-103-740-1-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 1,
    'CI_CommissionPriority': 2,
    'CI_CommissionType': 1,
    'CI_Region': 1,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1396/05/03',
    'Commission': 'كميسيون يك',
    'CommissionDate': '1400/08/03',
    'CommissionDateExpert': '1399/11/07',
    'CommissionState': 'Commission1',
    'CommissionType': 'بدوي',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1400/08/03',
    'ExpertName': 'وحيد زاهد (ZahedV)',
    'GuidAgent': null,
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': false,
    'IsRelapse': false,
    'IsVote': -1,
    'LaterTime': 1691,
    'LegalExpertComments': '',
    'NidCommission': '01dd1154-3ccf-4fd2-8743-8624620e3922',
    'NidProc': '519ce283-9c2b-4331-97e9-75a87e7c2b3e',
    'NidTask': 'd60fd93e-8eb0-401a-8f92-c344b1ecbc18',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': '',
    'OwnerName': ' شرکت پتک البرز',
    'OwnerNationalCode': null,
    'OwnerTelNo': '',
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '1398/06/31',
    'Regplaque': '',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 140184,
    'SendDate': '1396/05/03',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون1',
    'UrbanNidRequest': 309570,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': null,
    'VoterUserName': '                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ',
    'WorkflowTitel': null,
    'X': null,
    'Y': null
  },
  {
    'Address': 'تهران قديم کوچه شهروند بن بست شب آهنگ ',
    'AgentCount': 4,
    'AgentName': 'نماينده وزارت كشور | 1400/06/02  2:28 PM - نماينده دادگستري | 1400/06/02  2:28 PM - نماينده شوراي شهر | 1400/06/02  3:08 PM - نماينده وزارت كشور | 1400/06/02  3:13 PM',
    'BackStateTitle': 'تست',
    'BillNo': null,
    'BizCode': '1-3-46-192-1-0-0',
    'BizCodeMap': '1-3-46-192-1-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 1,
    'CI_CommissionPriority': 1,
    'CI_CommissionType': 1,
    'CI_Region': 1,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1396/05/03',
    'Commission': 'كميسيون يك',
    'CommissionDate': '1400/04/08',
    'CommissionDateExpert': '1400/01/29',
    'CommissionState': 'Commission1',
    'CommissionType': 'بدوي',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1400/04/08',
    'ExpertName': 'وحيد زاهد (ZahedV)',
    'GuidAgent': 'd4120c1b-8dce-40cd-ab74-f7d6cd864790 - 7ae0777c-44d5-4744-a432-6100ee60e3b9 - 8b7e86af-0172-4917-853b-4397c10356f9 - 6ea84027-e8ad-4bf6-829f-641332fd8d9b',
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': true,
    'IsRelapse': false,
    'IsVote': 1,
    'LaterTime': 1691,
    'LegalExpertComments': '',
    'NidCommission': 'fd3524de-e3a5-49b6-ba85-97047b08d0af',
    'NidProc': '1c826284-db5e-4384-8287-94fa73804f32',
    'NidTask': 'd60fd93e-8eb0-401a-8f92-c344b1ecbc18',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': '',
    'OwnerName': 'زهرا حکمی پور',
    'OwnerNationalCode': null,
    'OwnerTelNo': '',
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '1398/06/31',
    'Regplaque': 'اصلی(1925) - فرعی(1/9) - قطعه(8)',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 140182,
    'SendDate': '1396/05/03',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون1',
    'UrbanNidRequest': 325520,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': '1400/06/02',
    'VoterUserName': 'وحید زاهد (ZahedV)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ',
    'WorkflowTitel': null,
    'X': null,
    'Y': null
  },
  {
    'Address': 'ناصر آباد کوچه قاسمي -بن بست اول',
    'AgentCount': 2,
    'AgentName': 'نماينده وزارت كشور | 1400/06/27  2:46 PM - نماينده وزارت كشور | 1400/06/27  2:46 PM',
    'BackStateTitle': 'ماده صد منطقه 1',
    'BillNo': null,
    'BizCode': '1-8-59-752-1-0-0',
    'BizCodeMap': '1-8-59-752-1-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 2,
    'CI_CommissionPriority': 0,
    'CI_CommissionType': 1,
    'CI_Region': 1,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1396/05/01',
    'Commission': 'كميسيون دو',
    'CommissionDate': '1400/02/13',
    'CommissionDateExpert': '1396/07/15',
    'CommissionState': 'Tozi',
    'CommissionType': 'بدوي',
    'CompeletPrecent': 30,
    'DateCommissionExpert': '1400/02/13',
    'ExpertName': 'وحيد زاهد (ZahedV)',
    'GuidAgent': '6ea84027-e8ad-4bf6-829f-641332fd8d9b - 7bc16d9a-9ac4-47af-bc28-adad1622a054',
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': true,
    'IsRelapse': true,
    'IsVote': 1,
    'LaterTime': 1693,
    'LegalExpertComments': '',
    'NidCommission': 'f12197a4-0c44-44c7-9a21-25a23664ed7c',
    'NidProc': '385a4487-8861-4492-a78f-3c40b6455b72',
    'NidTask': 'c399c102-5f2e-469e-b8af-922e89fef4a4',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': '',
    'OwnerName': 'رقیه  وکیلی',
    'OwnerNationalCode': null,
    'OwnerTelNo': '',
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '1396/07/15',
    'Regplaque': 'اصلی(44) - فرعی() - قطعه()',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 140179,
    'SendDate': '1396/05/01',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'توزیع شده',
    'UrbanNidRequest': 340214,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': '1396/09/25',
    'VoterUserName': 'sa sa (sa)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ',
    'WorkflowTitel': null,
    'X': null,
    'Y': null
  },
  {
    'Address': '-فاز دوم ولايت--',
    'AgentCount': 0,
    'AgentName': null,
    'BackStateTitle': null,
    'BillNo': null,
    'BizCode': '2-12-144-2-1-0-0',
    'BizCodeMap': '2-12-144-2-1-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 1,
    'CI_CommissionPriority': 0,
    'CI_CommissionType': 4,
    'CI_Region': 2,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1394/09/04',
    'Commission': 'كميسيون يك',
    'CommissionDate': '1400/08/03',
    'CommissionDateExpert': '1395/06/08',
    'CommissionState': 'Commission1',
    'CommissionType': 'همعرض',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1400/08/03',
    'ExpertName': 'sa sa (sa)',
    'GuidAgent': null,
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': true,
    'IsRelapse': true,
    'IsVote': -1,
    'LaterTime': 2299,
    'LegalExpertComments': '',
    'NidCommission': 'cd129a50-b627-462a-9913-bbb0e6239aae',
    'NidProc': '11282095-bfd2-4f60-97cf-e9bc4a528043',
    'NidTask': 'd60fd93e-8eb0-401a-8f92-c344b1ecbc18',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': null,
    'OwnerName': 'محمدحسن شعباني',
    'OwnerNationalCode': null,
    'OwnerTelNo': null,
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '',
    'Regplaque': 'اصلي(34) - فرعي(9/691) - قطعه(0)',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 140036,
    'SendDate': '1394/09/04',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون1',
    'UrbanNidRequest': 181789,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': null,
    'VoterUserName': '                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ',
    'WorkflowTitel': 'کمیسیون ماده صد',
    'X': null,
    'Y': null
  },
  {
    'Address': 'ناحيه چوبيندر خيابان امراله کوچه ولي اله رضايي',
    'AgentCount': 1,
    'AgentName': 'نماينده وزارت كشور | 1400/06/27  1:50 PM',
    'BackStateTitle': null,
    'BillNo': null,
    'BizCode': '1-2-48-834-1-0-0',
    'BizCodeMap': '1-2-48-834-1-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 1,
    'CI_CommissionPriority': 0,
    'CI_CommissionType': 1,
    'CI_Region': 1,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1394/08/10',
    'Commission': 'كميسيون يك',
    'CommissionDate': '1395/08/05',
    'CommissionDateExpert': '1398/12/14',
    'CommissionState': 'Commission1',
    'CommissionType': 'بدوي',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1395/08/05',
    'ExpertName': 'مدير سيستم (sa)',
    'GuidAgent': '7bc16d9a-9ac4-47af-bc28-adad1622a054',
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': true,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': true,
    'IsRelapse': false,
    'IsVote': 7,
    'LaterTime': 2323,
    'LegalExpertComments': '',
    'NidCommission': '36d7277d-7a8f-41ba-b88e-89dc029e6318',
    'NidProc': '71e78477-cec7-4163-a265-593b26b368c1',
    'NidTask': 'd60fd93e-8eb0-401a-8f92-c344b1ecbc18',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': null,
    'OwnerName': 'غلامعلی صالحی',
    'OwnerNationalCode': null,
    'OwnerTelNo': null,
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '',
    'Regplaque': '',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 140022,
    'SendDate': '1394/08/10',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون1',
    'UrbanNidRequest': 169294,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': '1396/11/21',
    'VoterUserName': '0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ',
    'WorkflowTitel': 'کمیسیون ماده صد',
    'X': null,
    'Y': null
  },
  {
    'Address': 'ابتداي نوروزيان بر کانال آبرساني---',
    'AgentCount': 0,
    'AgentName': null,
    'BackStateTitle': null,
    'BillNo': null,
    'BizCode': '3-4-1-355-1-0-0',
    'BizCodeMap': '3-4-1-355-1-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 3,
    'CI_CommissionPriority': 0,
    'CI_CommissionType': 2,
    'CI_Region': 3,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1394/04/31',
    'Commission': 'كميسيون سه',
    'CommissionDate': '1400/08/03',
    'CommissionDateExpert': '1394/06/22',
    'CommissionState': 'Commission5',
    'CommissionType': 'تجديد نظر',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1400/08/03',
    'ExpertName': 'عليرضا صالحي (SalehiA)',
    'GuidAgent': null,
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': true,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': true,
    'IsRelapse': false,
    'IsVote': -1,
    'LaterTime': 2425,
    'LegalExpertComments': 'sserrdg',
    'NidCommission': 'd326123d-9567-4111-bb48-65931e6d369c',
    'NidProc': '9a33efbd-ac76-4f51-94da-d64cd2a7a67a',
    'NidTask': '92911c7a-2e1a-4f7d-9497-64ed37249e53',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': null,
    'OwnerName': 'شعبان صادقي',
    'OwnerNationalCode': null,
    'OwnerTelNo': null,
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '1398/03/05',
    'Regplaque': 'اصلي(53) - فرعي(قولنامه اي) - قطعه()',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 139999,
    'SendDate': '1394/04/31',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون5',
    'UrbanNidRequest': 131076,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': null,
    'VoterUserName': '0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ',
    'WorkflowTitel': 'کميسيون ماده صد',
    'X': null,
    'Y': null
  },
  {
    'Address': 'خيابان منتظزي جديد کوچه مرادي  پلاک 18',
    'AgentCount': 0,
    'AgentName': null,
    'BackStateTitle': null,
    'BillNo': null,
    'BizCode': '1-6-9-5-1-0-0',
    'BizCodeMap': '1-6-9-5-1-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 1,
    'CI_CommissionPriority': 1,
    'CI_CommissionType': 1,
    'CI_Region': 1,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1395/08/06',
    'Commission': 'كميسيون يك',
    'CommissionDate': '1400/08/03',
    'CommissionDateExpert': '1398/06/12',
    'CommissionState': 'Commission1',
    'CommissionType': 'بدوي',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1400/08/03',
    'ExpertName': 'مدير سيستم (sa)',
    'GuidAgent': null,
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': false,
    'IsRelapse': false,
    'IsVote': -1,
    'LaterTime': 1962,
    'LegalExpertComments': '',
    'NidCommission': '341ff8ff-665b-4012-b279-dc15fe88664d',
    'NidProc': 'ee1aca7d-1605-48ca-bb5f-eb86b2110e0c',
    'NidTask': 'd60fd93e-8eb0-401a-8f92-c344b1ecbc18',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': null,
    'OwnerName': 'وراث مرحوم بهرام محمد خانلو',
    'OwnerNationalCode': null,
    'OwnerTelNo': null,
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '1398/03/05',
    'Regplaque': 'اصلي(65) - فرعي(187/19) - قطعه()',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 139936,
    'SendDate': '1395/08/06',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون1',
    'UrbanNidRequest': 180883,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': null,
    'VoterUserName': '                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ',
    'WorkflowTitel': 'استعلام دفترخانه نقل و انتقال',
    'X': null,
    'Y': null
  },
  {
    'Address': 'بلوار سعادت---ميقات 10 پلاک 74',
    'AgentCount': 0,
    'AgentName': null,
    'BackStateTitle': null,
    'BillNo': null,
    'BizCode': '2-17-241-11-1-0-0',
    'BizCodeMap': '2-17-241-11-1-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 2,
    'CI_CommissionPriority': 0,
    'CI_CommissionType': 1,
    'CI_Region': 2,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1394/04/30',
    'Commission': 'كميسيون دو',
    'CommissionDate': '1398/03/05',
    'CommissionDateExpert': '1394/06/22',
    'CommissionState': 'Commission6',
    'CommissionType': 'بدوي',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1398/03/05',
    'ExpertName': null,
    'GuidAgent': null,
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': true,
    'IsRelapse': false,
    'IsVote': 1,
    'LaterTime': 2426,
    'LegalExpertComments': '',
    'NidCommission': 'c04ffbea-9f0b-4313-8b10-94b87667182c',
    'NidProc': 'ad00feb7-d3d1-4591-863d-49614513d877',
    'NidTask': '953a90f6-53e6-4ec1-a5be-b9d0dcf79b94',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': null,
    'OwnerName': 'داود  گل پرست وكا لتا از طرف علي اصغر كاشي ها ',
    'OwnerNationalCode': null,
    'OwnerTelNo': null,
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '',
    'Regplaque': 'اصلي(36) - فرعي(1709) - قطعه(1)',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 139917,
    'SendDate': '1394/04/30',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون6',
    'UrbanNidRequest': 161675,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': '1399/02/20',
    'VoterUserName': 'علیرضا صالحی (SalehiA)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ',
    'WorkflowTitel': 'کمیسیون ماده صد',
    'X': null,
    'Y': null
  },
  {
    'Address': 'خيابان شهيد انصاري - کوچه داماد - کوچه شهاب - انتهاي بن بست پلاک 38',
    'AgentCount': 0,
    'AgentName': null,
    'BackStateTitle': null,
    'BillNo': null,
    'BizCode': '1-5-11-27-1-0-0',
    'BizCodeMap': '1-5-11-27-1-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 1,
    'CI_CommissionPriority': 0,
    'CI_CommissionType': 3,
    'CI_Region': 1,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1394/04/24',
    'Commission': 'كميسيون يك',
    'CommissionDate': '1400/08/03',
    'CommissionDateExpert': '1394/04/29',
    'CommissionState': 'Commission1',
    'CommissionType': 'همعرض قم',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1400/08/03',
    'ExpertName': 'وحيد زاهد (ZahedV)',
    'GuidAgent': null,
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': true,
    'IsRelapse': false,
    'IsVote': -1,
    'LaterTime': 2432,
    'LegalExpertComments': '',
    'NidCommission': 'a04f511f-0cbc-4bc3-8292-05ca91009491',
    'NidProc': '137dc6c8-aab7-4906-8202-a152c397cd61',
    'NidTask': 'd60fd93e-8eb0-401a-8f92-c344b1ecbc18',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': null,
    'OwnerName': 'حسین آشوري و شرکاء',
    'OwnerNationalCode': null,
    'OwnerTelNo': null,
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '',
    'Regplaque': 'اصلي(1520) - فرعي() - قطعه()',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 139902,
    'SendDate': '1394/04/24',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون1',
    'UrbanNidRequest': 168816,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': null,
    'VoterUserName': '                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ',
    'WorkflowTitel': 'پایانکار',
    'X': null,
    'Y': null
  },
  {
    'Address': 'حسن آباد نبش فلکه ',
    'AgentCount': 0,
    'AgentName': null,
    'BackStateTitle': null,
    'BillNo': null,
    'BizCode': '3-6-120-450-1-0-0',
    'BizCodeMap': '3-6-120-450-1-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 3,
    'CI_CommissionPriority': 0,
    'CI_CommissionType': 5,
    'CI_Region': 3,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1394/04/21',
    'Commission': 'كميسيون سه',
    'CommissionDate': '1400/08/03',
    'CommissionDateExpert': '1394/08/12',
    'CommissionState': 'Commission3',
    'CommissionType': 'عدم پرداخت جريمه',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1400/08/03',
    'ExpertName': 'وحيد زاهد (ZahedV)',
    'GuidAgent': null,
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': true,
    'IsRelapse': false,
    'IsVote': -1,
    'LaterTime': 2435,
    'LegalExpertComments': '',
    'NidCommission': 'efa7a105-4afe-44c0-aae1-0625e27bf47a',
    'NidProc': '0d32482d-6843-4efc-b7d0-ec1d76ebbbf5',
    'NidTask': '22d6be51-51b5-4be7-b790-ca7bf8b22522',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': null,
    'OwnerName': 'مهدی  کشاورز فهیم وشرکا ',
    'OwnerNationalCode': null,
    'OwnerTelNo': null,
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '',
    'Regplaque': 'اصلي(32) - فرعي() - قطعه()',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 139831,
    'SendDate': '1394/04/21',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون3',
    'UrbanNidRequest': 128417,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': null,
    'VoterUserName': '                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ',
    'WorkflowTitel': 'کميسيون ماده صد',
    'X': null,
    'Y': null
  },
  {
    'Address': 'پونک بلوک 8 قطعه 25خيابان بشارت خيابان انتظار14 کوچه انتظار2',
    'AgentCount': 0,
    'AgentName': null,
    'BackStateTitle': null,
    'BillNo': null,
    'BizCode': '3-7-70-15-1-0-0',
    'BizCodeMap': '3-7-70-15-1-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 4,
    'CI_CommissionPriority': 0,
    'CI_CommissionType': 1,
    'CI_Region': 3,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1394/04/31',
    'Commission': 'كميسيون چهار',
    'CommissionDate': '1398/11/20',
    'CommissionDateExpert': '1394/10/30',
    'CommissionState': 'Commission4',
    'CommissionType': 'بدوي',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1398/11/20',
    'ExpertName': null,
    'GuidAgent': null,
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': false,
    'IsRelapse': true,
    'IsVote': -1,
    'LaterTime': 2425,
    'LegalExpertComments': '',
    'NidCommission': 'c84289bb-9bc4-4233-8c48-010e1ba22d13',
    'NidProc': '6cfb5bd4-e0c0-40ce-b2e8-3f1164578eb5',
    'NidTask': 'd3c66825-d48d-47f0-af51-9a8c44cceed5',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': null,
    'OwnerName': 'پری  احمدی ',
    'OwnerNationalCode': null,
    'OwnerTelNo': null,
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '',
    'Regplaque': 'اصلي(36) - فرعي(14/15/8920) - قطعه(25)',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 139800,
    'SendDate': '1394/04/31',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون4',
    'UrbanNidRequest': 163352,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': null,
    'VoterUserName': '                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ',
    'WorkflowTitel': 'کميسيون ماده صد',
    'X': null,
    'Y': null
  },
  {
    'Address': 'ضلع عرب مينودر زمين وشتق بالاي کا نال-مجتمع سنگ فروشان--',
    'AgentCount': 0,
    'AgentName': null,
    'BackStateTitle': null,
    'BillNo': null,
    'BizCode': '3-13-1-19-1-0-0',
    'BizCodeMap': '3-13-1-19-1-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 1,
    'CI_CommissionPriority': 0,
    'CI_CommissionType': 4,
    'CI_Region': 3,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1394/04/22',
    'Commission': 'كميسيون يك',
    'CommissionDate': '1398/12/27',
    'CommissionDateExpert': '1394/04/24',
    'CommissionState': 'Commission1',
    'CommissionType': 'همعرض',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1398/12/27',
    'ExpertName': null,
    'GuidAgent': null,
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': true,
    'IsRelapse': false,
    'IsVote': -1,
    'LaterTime': 2434,
    'LegalExpertComments': '',
    'NidCommission': 'a75ccbc7-0edf-4a60-8491-0252843c3326',
    'NidProc': 'cefbe16d-d1c4-41af-939e-268a6ba0a0bd',
    'NidTask': 'd60fd93e-8eb0-401a-8f92-c344b1ecbc18',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': null,
    'OwnerName': 'اله بخش  غياثوند وشرکاء',
    'OwnerNationalCode': null,
    'OwnerTelNo': null,
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '',
    'Regplaque': 'اصلي(قولنامه اي) - فرعي() - قطعه()',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 139760,
    'SendDate': '1394/04/22',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون1',
    'UrbanNidRequest': 91089,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': null,
    'VoterUserName': '                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ',
    'WorkflowTitel': null,
    'X': null,
    'Y': null
  },
  {
    'Address': 'شهرک مهديه خيابان ابوريحان بيروني کوچه بهار 13 پلاک 20',
    'AgentCount': 0,
    'AgentName': null,
    'BackStateTitle': null,
    'BillNo': null,
    'BizCode': '3-8-69-5-1-0-0',
    'BizCodeMap': '3-8-69-5-1-0-0',
    'CI_BoundCode': 0,
    'CI_Commission': 3,
    'CI_CommissionPriority': 0,
    'CI_CommissionType': 1,
    'CI_Region': 3,
    'CI_VoteCorrection': 0,
    'ColorInKartabl': null,
    'ComEnterDate': '1394/04/07',
    'Commission': 'كميسيون سه',
    'CommissionDate': '1399/12/05',
    'CommissionDateExpert': '1394/04/10',
    'CommissionState': 'Commission3',
    'CommissionType': 'بدوي',
    'CompeletPrecent': 90,
    'DateCommissionExpert': '1399/12/05',
    'ExpertName': 'وحيد زاهد (ZahedV)',
    'GuidAgent': null,
    'HasComments': false,
    'HasGharar': false,
    'HasHoghoghi': false,
    'HasLegalExpert': false,
    'HasTasmim': false,
    'IsKarbari': false,
    'IsLaterDate': true,
    'IsMeeting': false,
    'IsPast': true,
    'IsRelapse': false,
    'IsVote': 4,
    'LaterTime': 2449,
    'LegalExpertComments': '',
    'NidCommission': 'a714bc18-f11e-44e1-8095-0bbda9f0d961',
    'NidProc': '21baff49-75d3-4dca-926c-4c246a37d2a1',
    'NidTask': '22d6be51-51b5-4be7-b790-ca7bf8b22522',
    'NidUser': '00000000-0000-0000-0000-000000000000',
    'NidWorkItem': 0,
    'OwnerCellNo': null,
    'OwnerName': 'فرهاد مسگري',
    'OwnerNationalCode': null,
    'OwnerTelNo': null,
    'PenaltyValue': 0,
    'PreCode': null,
    'ProcBookmark': null,
    'ProcInitiatorName': null,
    'RandomCommissionDate': '',
    'Regplaque': 'اصلي(36) - فرعي(17778) - قطعه()',
    'Requester': null,
    'ResponseGharar': false,
    'SecrNo': 139676,
    'SendDate': '1394/04/07',
    'SysCI_RequestBy': 1,
    'TaskTitel': 'کمیسیون3',
    'UrbanNidRequest': 167408,
    'UrbanRequestDate': null,
    'UsingGroup_Mojood': null,
    'VoteDate': '1394/04/07',
    'VoterUserName': 'وحید زاهد (ZahedV)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ',
    'WorkflowTitel': 'پايانکار',
    'X': null,
    'Y': null
  }].map(Object.freeze)
